

/*
 * Workflow
 * This API uses the workflow capability of SAP Build Process Automation. With the API, you can, for example, start new workflow instances and work with tasks.  Note: These APIs are designed for loosely coupled clients. This means:  - If SAP Build Process Automation adds fields to responses, the API version number does not increase. Your client must ignore new fields. - The order of fields in responses and of entries in arrays may change. This applies unless the API provides an explicit means to specify the desired order. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.demo.spa.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import customer.demo.spa.model.AttachmentsContextGroupsValueRefsInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * AttachmentsContextGroupsValue
 */

// CHECKSTYLE:OFF
public class AttachmentsContextGroupsValue 
// CHECKSTYLE:ON
{
  @JsonProperty("folder")
  private String folder;

  @JsonProperty("refs")
  private List<AttachmentsContextGroupsValueRefsInner> refs = new ArrayList<>();

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the folder of this {@link AttachmentsContextGroupsValue} instance and return the same instance.
   *
   * @param folder  A folder that shall be used for uploading files at the remote repository for this group (i.e. relative to the root folder)
   * @return The same instance of this {@link AttachmentsContextGroupsValue} class
   */
   @Nonnull public AttachmentsContextGroupsValue folder(@Nonnull final String folder) {
    this.folder = folder;
    return this;
  }

   /**
   * A folder that shall be used for uploading files at the remote repository for this group (i.e. relative to the root folder)
   * @return folder  The folder of this {@link AttachmentsContextGroupsValue} instance.
  **/
  @Nonnull public String getFolder() {
    return folder;
  }

  /**
  * Set the folder of this {@link AttachmentsContextGroupsValue} instance.
  *
  * @param folder  A folder that shall be used for uploading files at the remote repository for this group (i.e. relative to the root folder)
  */
  public void setFolder( @Nonnull final String folder) {
    this.folder = folder;
  }

   /**
   * Set the refs of this {@link AttachmentsContextGroupsValue} instance and return the same instance.
   *
   * @param refs  A list of references to files in the remote repository
   * @return The same instance of this {@link AttachmentsContextGroupsValue} class
   */
   @Nonnull public AttachmentsContextGroupsValue refs(@Nonnull final List<AttachmentsContextGroupsValueRefsInner> refs) {
    this.refs = refs;
    return this;
  }
  /**
  * Add one refs instance to this {@link AttachmentsContextGroupsValue}.
  * @param refsItem The refs that should be added
  * @return The same instance of type {@link AttachmentsContextGroupsValue}
  */
  @Nonnull public AttachmentsContextGroupsValue addrefsItem( @Nonnull final AttachmentsContextGroupsValueRefsInner refsItem) {
    if (this.refs == null) {
      this.refs = new ArrayList<>();
    }
    this.refs.add(refsItem);
    return this;
  }

   /**
   * A list of references to files in the remote repository
   * @return refs  The refs of this {@link AttachmentsContextGroupsValue} instance.
  **/
  @Nonnull public List<AttachmentsContextGroupsValueRefsInner> getRefs() {
    return refs;
  }

  /**
  * Set the refs of this {@link AttachmentsContextGroupsValue} instance.
  *
  * @param refs  A list of references to files in the remote repository
  */
  public void setRefs( @Nonnull final List<AttachmentsContextGroupsValueRefsInner> refs) {
    this.refs = refs;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link AttachmentsContextGroupsValue}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link AttachmentsContextGroupsValue} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("AttachmentsContextGroupsValue has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link AttachmentsContextGroupsValue} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final AttachmentsContextGroupsValue attachmentsContextGroupsValue = (AttachmentsContextGroupsValue) o;
    return Objects.equals(this.cloudSdkCustomFields, attachmentsContextGroupsValue.cloudSdkCustomFields) &&
        Objects.equals(this.folder, attachmentsContextGroupsValue.folder) &&
        Objects.equals(this.refs, attachmentsContextGroupsValue.refs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(folder, refs, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class AttachmentsContextGroupsValue {\n");
    sb.append("    folder: ").append(toIndentedString(folder)).append("\n");
    sb.append("    refs: ").append(toIndentedString(refs)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

