

/*
 * Workflow
 * This API uses the workflow capability of SAP Build Process Automation. With the API, you can, for example, start new workflow instances and work with tasks.  Note: These APIs are designed for loosely coupled clients. This means:  - If SAP Build Process Automation adds fields to responses, the API version number does not increase. Your client must ignore new fields. - The order of fields in responses and of entries in arrays may change. This applies unless the API provides an explicit means to specify the desired order. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.demo.spa.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import customer.demo.spa.model.JobError;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * Job
 */

// CHECKSTYLE:OFF
public class Job 
// CHECKSTYLE:ON
{
  /**
   * The status of the job.
   */
  public enum StatusEnum {
    /**
    * The RUNNING option of this Job
    */
    RUNNING("RUNNING"),
    
    /**
    * The ERRONEOUS option of this Job
    */
    ERRONEOUS("ERRONEOUS");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type Job
    */
    @JsonCreator
    @Nonnull public static StatusEnum fromValue(@Nonnull final String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("status")
  private StatusEnum status;

  @JsonProperty("details")
  private Object details;

  @JsonProperty("error")
  private JobError error;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the status of this {@link Job} instance and return the same instance.
   *
   * @param status  The status of the job.
   * @return The same instance of this {@link Job} class
   */
   @Nonnull public Job status(@Nonnull final StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * The status of the job.
   * @return status  The status of this {@link Job} instance.
  **/
  @Nonnull public StatusEnum getStatus() {
    return status;
  }

  /**
  * Set the status of this {@link Job} instance.
  *
  * @param status  The status of the job.
  */
  public void setStatus( @Nonnull final StatusEnum status) {
    this.status = status;
  }

   /**
   * Set the details of this {@link Job} instance and return the same instance.
   *
   * @param details  The details of the job.
   * @return The same instance of this {@link Job} class
   */
   @Nonnull public Job details(@Nonnull final Object details) {
    this.details = details;
    return this;
  }

   /**
   * The details of the job.
   * @return details  The details of this {@link Job} instance.
  **/
  @Nonnull public Object getDetails() {
    return details;
  }

  /**
  * Set the details of this {@link Job} instance.
  *
  * @param details  The details of the job.
  */
  public void setDetails( @Nonnull final Object details) {
    this.details = details;
  }

   /**
   * Set the error of this {@link Job} instance and return the same instance.
   *
   * @param error  The error of this {@link Job}
   * @return The same instance of this {@link Job} class
   */
   @Nonnull public Job error(@Nonnull final JobError error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error  The error of this {@link Job} instance.
  **/
  @Nonnull public JobError getError() {
    return error;
  }

  /**
  * Set the error of this {@link Job} instance.
  *
  * @param error  The error of this {@link Job}
  */
  public void setError( @Nonnull final JobError error) {
    this.error = error;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link Job}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link Job} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("Job has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link Job} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final Job job = (Job) o;
    return Objects.equals(this.cloudSdkCustomFields, job.cloudSdkCustomFields) &&
        Objects.equals(this.status, job.status) &&
        Objects.equals(this.details, job.details) &&
        Objects.equals(this.error, job.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, details, error, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class Job {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

