

/*
 * Workflow
 * This API uses the workflow capability of SAP Build Process Automation. With the API, you can, for example, start new workflow instances and work with tasks.  Note: These APIs are designed for loosely coupled clients. This means:  - If SAP Build Process Automation adds fields to responses, the API version number does not increase. Your client must ignore new fields. - The order of fields in responses and of entries in arrays may change. This applies unless the API provides an explicit means to specify the desired order. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.demo.spa.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * SendMessagePayload
 */

// CHECKSTYLE:OFF
public class SendMessagePayload 
// CHECKSTYLE:ON
{
  @JsonProperty("context")
  private Object context;

  @JsonProperty("definitionId")
  private String definitionId;

  @JsonProperty("workflowInstanceId")
  private String workflowInstanceId;

  @JsonProperty("workflowDefinitionId")
  private String workflowDefinitionId;

  @JsonProperty("businessKey")
  private String businessKey;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the context of this {@link SendMessagePayload} instance and return the same instance.
   *
   * @param context  Specify the data to be written into the response variable defined on the intermediate message event.
   * @return The same instance of this {@link SendMessagePayload} class
   */
   @Nonnull public SendMessagePayload context(@Nonnull final Object context) {
    this.context = context;
    return this;
  }

   /**
   * Specify the data to be written into the response variable defined on the intermediate message event.
   * @return context  The context of this {@link SendMessagePayload} instance.
  **/
  @Nonnull public Object getContext() {
    return context;
  }

  /**
  * Set the context of this {@link SendMessagePayload} instance.
  *
  * @param context  Specify the data to be written into the response variable defined on the intermediate message event.
  */
  public void setContext( @Nonnull final Object context) {
    this.context = context;
  }

   /**
   * Set the definitionId of this {@link SendMessagePayload} instance and return the same instance.
   *
   * @param definitionId  Specify the definition ID of the message. This corresponds to the \&quot;Message Name\&quot; field on the intermediate message event. The definition ID is at most 128 characters long.
   * @return The same instance of this {@link SendMessagePayload} class
   */
   @Nonnull public SendMessagePayload definitionId(@Nonnull final String definitionId) {
    this.definitionId = definitionId;
    return this;
  }

   /**
   * Specify the definition ID of the message. This corresponds to the \&quot;Message Name\&quot; field on the intermediate message event. The definition ID is at most 128 characters long.
   * @return definitionId  The definitionId of this {@link SendMessagePayload} instance.
  **/
  @Nonnull public String getDefinitionId() {
    return definitionId;
  }

  /**
  * Set the definitionId of this {@link SendMessagePayload} instance.
  *
  * @param definitionId  Specify the definition ID of the message. This corresponds to the \&quot;Message Name\&quot; field on the intermediate message event. The definition ID is at most 128 characters long.
  */
  public void setDefinitionId( @Nonnull final String definitionId) {
    this.definitionId = definitionId;
  }

   /**
   * Set the workflowInstanceId of this {@link SendMessagePayload} instance and return the same instance.
   *
   * @param workflowInstanceId  Specify the workflow instance ID of the workflow instance that should receive the message. The workflow instance ID is 36 characters long. You must specify either workflowInstanceId or the pair of workflowDefinitionId and businessKey.
   * @return The same instance of this {@link SendMessagePayload} class
   */
   @Nonnull public SendMessagePayload workflowInstanceId(@Nonnull final String workflowInstanceId) {
    this.workflowInstanceId = workflowInstanceId;
    return this;
  }

   /**
   * Specify the workflow instance ID of the workflow instance that should receive the message. The workflow instance ID is 36 characters long. You must specify either workflowInstanceId or the pair of workflowDefinitionId and businessKey.
   * @return workflowInstanceId  The workflowInstanceId of this {@link SendMessagePayload} instance.
  **/
  @Nonnull public String getWorkflowInstanceId() {
    return workflowInstanceId;
  }

  /**
  * Set the workflowInstanceId of this {@link SendMessagePayload} instance.
  *
  * @param workflowInstanceId  Specify the workflow instance ID of the workflow instance that should receive the message. The workflow instance ID is 36 characters long. You must specify either workflowInstanceId or the pair of workflowDefinitionId and businessKey.
  */
  public void setWorkflowInstanceId( @Nonnull final String workflowInstanceId) {
    this.workflowInstanceId = workflowInstanceId;
  }

   /**
   * Set the workflowDefinitionId of this {@link SendMessagePayload} instance and return the same instance.
   *
   * @param workflowDefinitionId  Specify the definition ID of the workflow the message belongs to. The definition ID is at most 64 characters long. You must specify either workflowInstanceId or the pair of workflowDefinitionId and businessKey.
   * @return The same instance of this {@link SendMessagePayload} class
   */
   @Nonnull public SendMessagePayload workflowDefinitionId(@Nonnull final String workflowDefinitionId) {
    this.workflowDefinitionId = workflowDefinitionId;
    return this;
  }

   /**
   * Specify the definition ID of the workflow the message belongs to. The definition ID is at most 64 characters long. You must specify either workflowInstanceId or the pair of workflowDefinitionId and businessKey.
   * @return workflowDefinitionId  The workflowDefinitionId of this {@link SendMessagePayload} instance.
  **/
  @Nonnull public String getWorkflowDefinitionId() {
    return workflowDefinitionId;
  }

  /**
  * Set the workflowDefinitionId of this {@link SendMessagePayload} instance.
  *
  * @param workflowDefinitionId  Specify the definition ID of the workflow the message belongs to. The definition ID is at most 64 characters long. You must specify either workflowInstanceId or the pair of workflowDefinitionId and businessKey.
  */
  public void setWorkflowDefinitionId( @Nonnull final String workflowDefinitionId) {
    this.workflowDefinitionId = workflowDefinitionId;
  }

   /**
   * Set the businessKey of this {@link SendMessagePayload} instance and return the same instance.
   *
   * @param businessKey  Specify the business key of the workflow instance, that should receive the message. The business key of a workflow instance is limited to 255 characters. You must specify either workflowInstanceId or the pair of workflowDefinitionId and businessKey.
   * @return The same instance of this {@link SendMessagePayload} class
   */
   @Nonnull public SendMessagePayload businessKey(@Nonnull final String businessKey) {
    this.businessKey = businessKey;
    return this;
  }

   /**
   * Specify the business key of the workflow instance, that should receive the message. The business key of a workflow instance is limited to 255 characters. You must specify either workflowInstanceId or the pair of workflowDefinitionId and businessKey.
   * @return businessKey  The businessKey of this {@link SendMessagePayload} instance.
  **/
  @Nonnull public String getBusinessKey() {
    return businessKey;
  }

  /**
  * Set the businessKey of this {@link SendMessagePayload} instance.
  *
  * @param businessKey  Specify the business key of the workflow instance, that should receive the message. The business key of a workflow instance is limited to 255 characters. You must specify either workflowInstanceId or the pair of workflowDefinitionId and businessKey.
  */
  public void setBusinessKey( @Nonnull final String businessKey) {
    this.businessKey = businessKey;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link SendMessagePayload}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link SendMessagePayload} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("SendMessagePayload has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link SendMessagePayload} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final SendMessagePayload sendMessagePayload = (SendMessagePayload) o;
    return Objects.equals(this.cloudSdkCustomFields, sendMessagePayload.cloudSdkCustomFields) &&
        Objects.equals(this.context, sendMessagePayload.context) &&
        Objects.equals(this.definitionId, sendMessagePayload.definitionId) &&
        Objects.equals(this.workflowInstanceId, sendMessagePayload.workflowInstanceId) &&
        Objects.equals(this.workflowDefinitionId, sendMessagePayload.workflowDefinitionId) &&
        Objects.equals(this.businessKey, sendMessagePayload.businessKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(context, definitionId, workflowInstanceId, workflowDefinitionId, businessKey, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class SendMessagePayload {\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    definitionId: ").append(toIndentedString(definitionId)).append("\n");
    sb.append("    workflowInstanceId: ").append(toIndentedString(workflowInstanceId)).append("\n");
    sb.append("    workflowDefinitionId: ").append(toIndentedString(workflowDefinitionId)).append("\n");
    sb.append("    businessKey: ").append(toIndentedString(businessKey)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

