

/*
 * Workflow
 * This API uses the workflow capability of SAP Build Process Automation. With the API, you can, for example, start new workflow instances and work with tasks.  Note: These APIs are designed for loosely coupled clients. This means:  - If SAP Build Process Automation adds fields to responses, the API version number does not increase. Your client must ignore new fields. - The order of fields in responses and of entries in arrays may change. This applies unless the API provides an explicit means to specify the desired order. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.demo.spa.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * UpdateTaskInstancePayload
 */

// CHECKSTYLE:OFF
public class UpdateTaskInstancePayload 
// CHECKSTYLE:ON
{
  @JsonProperty("context")
  private Object context;

  /**
   * Specify the new status of the task instance.
   */
  public enum StatusEnum {
    /**
    * The COMPLETED option of this UpdateTaskInstancePayload
    */
    COMPLETED("COMPLETED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type UpdateTaskInstancePayload
    */
    @JsonCreator
    @Nonnull public static StatusEnum fromValue(@Nonnull final String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("status")
  private StatusEnum status;

  @JsonProperty("decision")
  private String decision;

  @JsonProperty("subject")
  private String subject;

  @JsonProperty("description")
  private String description;

  @JsonProperty("recipientUsers")
  private String recipientUsers;

  @JsonProperty("recipientGroups")
  private String recipientGroups;

  @JsonProperty("processor")
  private String processor;

  @JsonProperty("dueDate")
  private OffsetDateTime dueDate;

  /**
   * Specify the new priority of the task instance.
   */
  public enum PriorityEnum {
    /**
    * The VERY_HIGH option of this UpdateTaskInstancePayload
    */
    VERY_HIGH("VERY_HIGH"),
    
    /**
    * The HIGH option of this UpdateTaskInstancePayload
    */
    HIGH("HIGH"),
    
    /**
    * The MEDIUM option of this UpdateTaskInstancePayload
    */
    MEDIUM("MEDIUM"),
    
    /**
    * The LOW option of this UpdateTaskInstancePayload
    */
    LOW("LOW");

    private String value;

    PriorityEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type UpdateTaskInstancePayload
    */
    @JsonCreator
    @Nonnull public static PriorityEnum fromValue(@Nonnull final String value) {
      for (PriorityEnum b : PriorityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("priority")
  private PriorityEnum priority;

  @JsonProperty("confidenceLevel")
  private Double confidenceLevel;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the context of this {@link UpdateTaskInstancePayload} instance and return the same instance.
   *
   * @param context  The changes to the context of the workflow instance the user task belongs to.
   * @return The same instance of this {@link UpdateTaskInstancePayload} class
   */
   @Nonnull public UpdateTaskInstancePayload context(@Nonnull final Object context) {
    this.context = context;
    return this;
  }

   /**
   * The changes to the context of the workflow instance the user task belongs to.
   * @return context  The context of this {@link UpdateTaskInstancePayload} instance.
  **/
  @Nonnull public Object getContext() {
    return context;
  }

  /**
  * Set the context of this {@link UpdateTaskInstancePayload} instance.
  *
  * @param context  The changes to the context of the workflow instance the user task belongs to.
  */
  public void setContext( @Nonnull final Object context) {
    this.context = context;
  }

   /**
   * Set the status of this {@link UpdateTaskInstancePayload} instance and return the same instance.
   *
   * @param status  Specify the new status of the task instance.
   * @return The same instance of this {@link UpdateTaskInstancePayload} class
   */
   @Nonnull public UpdateTaskInstancePayload status(@Nonnull final StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Specify the new status of the task instance.
   * @return status  The status of this {@link UpdateTaskInstancePayload} instance.
  **/
  @Nonnull public StatusEnum getStatus() {
    return status;
  }

  /**
  * Set the status of this {@link UpdateTaskInstancePayload} instance.
  *
  * @param status  Specify the new status of the task instance.
  */
  public void setStatus( @Nonnull final StatusEnum status) {
    this.status = status;
  }

   /**
   * Set the decision of this {@link UpdateTaskInstancePayload} instance and return the same instance.
   *
   * @param decision  Specify the decision taken by the user when the task status is set to &#39;COMPLETED&#39;. The decision can be evaluated with a respective expression to adapt the control flow accordingly.
   * @return The same instance of this {@link UpdateTaskInstancePayload} class
   */
   @Nonnull public UpdateTaskInstancePayload decision(@Nonnull final String decision) {
    this.decision = decision;
    return this;
  }

   /**
   * Specify the decision taken by the user when the task status is set to &#39;COMPLETED&#39;. The decision can be evaluated with a respective expression to adapt the control flow accordingly.
   * @return decision  The decision of this {@link UpdateTaskInstancePayload} instance.
  **/
  @Nonnull public String getDecision() {
    return decision;
  }

  /**
  * Set the decision of this {@link UpdateTaskInstancePayload} instance.
  *
  * @param decision  Specify the decision taken by the user when the task status is set to &#39;COMPLETED&#39;. The decision can be evaluated with a respective expression to adapt the control flow accordingly.
  */
  public void setDecision( @Nonnull final String decision) {
    this.decision = decision;
  }

   /**
   * Set the subject of this {@link UpdateTaskInstancePayload} instance and return the same instance.
   *
   * @param subject  Specify the new subject of the task instance. The subject can be at most 255 characters long.  Note that patching a translated subject is not supported, i.e. GET requests executed on a translated user task do not display the patched text.
   * @return The same instance of this {@link UpdateTaskInstancePayload} class
   */
   @Nonnull public UpdateTaskInstancePayload subject(@Nonnull final String subject) {
    this.subject = subject;
    return this;
  }

   /**
   * Specify the new subject of the task instance. The subject can be at most 255 characters long.  Note that patching a translated subject is not supported, i.e. GET requests executed on a translated user task do not display the patched text.
   * @return subject  The subject of this {@link UpdateTaskInstancePayload} instance.
  **/
  @Nonnull public String getSubject() {
    return subject;
  }

  /**
  * Set the subject of this {@link UpdateTaskInstancePayload} instance.
  *
  * @param subject  Specify the new subject of the task instance. The subject can be at most 255 characters long.  Note that patching a translated subject is not supported, i.e. GET requests executed on a translated user task do not display the patched text.
  */
  public void setSubject( @Nonnull final String subject) {
    this.subject = subject;
  }

   /**
   * Set the description of this {@link UpdateTaskInstancePayload} instance and return the same instance.
   *
   * @param description  Specify the new description of the task instance. The description can be at most 4000 characters long.  Note that patching a translated description is not supported, i.e. GET requests executed on a translated user task do not display the patched text.
   * @return The same instance of this {@link UpdateTaskInstancePayload} class
   */
   @Nonnull public UpdateTaskInstancePayload description(@Nonnull final String description) {
    this.description = description;
    return this;
  }

   /**
   * Specify the new description of the task instance. The description can be at most 4000 characters long.  Note that patching a translated description is not supported, i.e. GET requests executed on a translated user task do not display the patched text.
   * @return description  The description of this {@link UpdateTaskInstancePayload} instance.
  **/
  @Nonnull public String getDescription() {
    return description;
  }

  /**
  * Set the description of this {@link UpdateTaskInstancePayload} instance.
  *
  * @param description  Specify the new description of the task instance. The description can be at most 4000 characters long.  Note that patching a translated description is not supported, i.e. GET requests executed on a translated user task do not display the patched text.
  */
  public void setDescription( @Nonnull final String description) {
    this.description = description;
  }

   /**
   * Set the recipientUsers of this {@link UpdateTaskInstancePayload} instance and return the same instance.
   *
   * @param recipientUsers  Specify the new recipient users of the task instance as a comma-separated list. Specify at most 100 recipient users. The ID of a recipient user can be at most 255 characters long.
   * @return The same instance of this {@link UpdateTaskInstancePayload} class
   */
   @Nonnull public UpdateTaskInstancePayload recipientUsers(@Nonnull final String recipientUsers) {
    this.recipientUsers = recipientUsers;
    return this;
  }

   /**
   * Specify the new recipient users of the task instance as a comma-separated list. Specify at most 100 recipient users. The ID of a recipient user can be at most 255 characters long.
   * @return recipientUsers  The recipientUsers of this {@link UpdateTaskInstancePayload} instance.
  **/
  @Nonnull public String getRecipientUsers() {
    return recipientUsers;
  }

  /**
  * Set the recipientUsers of this {@link UpdateTaskInstancePayload} instance.
  *
  * @param recipientUsers  Specify the new recipient users of the task instance as a comma-separated list. Specify at most 100 recipient users. The ID of a recipient user can be at most 255 characters long.
  */
  public void setRecipientUsers( @Nonnull final String recipientUsers) {
    this.recipientUsers = recipientUsers;
  }

   /**
   * Set the recipientGroups of this {@link UpdateTaskInstancePayload} instance and return the same instance.
   *
   * @param recipientGroups  Specify the new recipient groups of the task instance, as a comma-separated list. Specify at most 100 recipient groups. The ID of a recipient group can be at most 255 characters long.
   * @return The same instance of this {@link UpdateTaskInstancePayload} class
   */
   @Nonnull public UpdateTaskInstancePayload recipientGroups(@Nonnull final String recipientGroups) {
    this.recipientGroups = recipientGroups;
    return this;
  }

   /**
   * Specify the new recipient groups of the task instance, as a comma-separated list. Specify at most 100 recipient groups. The ID of a recipient group can be at most 255 characters long.
   * @return recipientGroups  The recipientGroups of this {@link UpdateTaskInstancePayload} instance.
  **/
  @Nonnull public String getRecipientGroups() {
    return recipientGroups;
  }

  /**
  * Set the recipientGroups of this {@link UpdateTaskInstancePayload} instance.
  *
  * @param recipientGroups  Specify the new recipient groups of the task instance, as a comma-separated list. Specify at most 100 recipient groups. The ID of a recipient group can be at most 255 characters long.
  */
  public void setRecipientGroups( @Nonnull final String recipientGroups) {
    this.recipientGroups = recipientGroups;
  }

   /**
   * Set the processor of this {@link UpdateTaskInstancePayload} instance and return the same instance.
   *
   * @param processor  Specify the new processor of the task instance. The ID of the processor can be at most 255 characters long and must not contain commas.
   * @return The same instance of this {@link UpdateTaskInstancePayload} class
   */
   @Nonnull public UpdateTaskInstancePayload processor(@Nonnull final String processor) {
    this.processor = processor;
    return this;
  }

   /**
   * Specify the new processor of the task instance. The ID of the processor can be at most 255 characters long and must not contain commas.
   * @return processor  The processor of this {@link UpdateTaskInstancePayload} instance.
  **/
  @Nonnull public String getProcessor() {
    return processor;
  }

  /**
  * Set the processor of this {@link UpdateTaskInstancePayload} instance.
  *
  * @param processor  Specify the new processor of the task instance. The ID of the processor can be at most 255 characters long and must not contain commas.
  */
  public void setProcessor( @Nonnull final String processor) {
    this.processor = processor;
  }

   /**
   * Set the dueDate of this {@link UpdateTaskInstancePayload} instance and return the same instance.
   *
   * @param dueDate  Specify the new due date of the task instance.
   * @return The same instance of this {@link UpdateTaskInstancePayload} class
   */
   @Nonnull public UpdateTaskInstancePayload dueDate(@Nonnull final OffsetDateTime dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * Specify the new due date of the task instance.
   * @return dueDate  The dueDate of this {@link UpdateTaskInstancePayload} instance.
  **/
  @Nonnull public OffsetDateTime getDueDate() {
    return dueDate;
  }

  /**
  * Set the dueDate of this {@link UpdateTaskInstancePayload} instance.
  *
  * @param dueDate  Specify the new due date of the task instance.
  */
  public void setDueDate( @Nonnull final OffsetDateTime dueDate) {
    this.dueDate = dueDate;
  }

   /**
   * Set the priority of this {@link UpdateTaskInstancePayload} instance and return the same instance.
   *
   * @param priority  Specify the new priority of the task instance.
   * @return The same instance of this {@link UpdateTaskInstancePayload} class
   */
   @Nonnull public UpdateTaskInstancePayload priority(@Nonnull final PriorityEnum priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Specify the new priority of the task instance.
   * @return priority  The priority of this {@link UpdateTaskInstancePayload} instance.
  **/
  @Nonnull public PriorityEnum getPriority() {
    return priority;
  }

  /**
  * Set the priority of this {@link UpdateTaskInstancePayload} instance.
  *
  * @param priority  Specify the new priority of the task instance.
  */
  public void setPriority( @Nonnull final PriorityEnum priority) {
    this.priority = priority;
  }

   /**
   * Set the confidenceLevel of this {@link UpdateTaskInstancePayload} instance and return the same instance.
   *
   * @param confidenceLevel  Specify the confidenceLevel for a task instance. The value must be between 0.0 and 1.0. To delete the confidenceLevel, specify a value of -1.0.
   * @return The same instance of this {@link UpdateTaskInstancePayload} class
   */
   @Nonnull public UpdateTaskInstancePayload confidenceLevel(@Nonnull final Double confidenceLevel) {
    this.confidenceLevel = confidenceLevel;
    return this;
  }

   /**
   * Specify the confidenceLevel for a task instance. The value must be between 0.0 and 1.0. To delete the confidenceLevel, specify a value of -1.0.
   * @return confidenceLevel  The confidenceLevel of this {@link UpdateTaskInstancePayload} instance.
  **/
  @Nonnull public Double getConfidenceLevel() {
    return confidenceLevel;
  }

  /**
  * Set the confidenceLevel of this {@link UpdateTaskInstancePayload} instance.
  *
  * @param confidenceLevel  Specify the confidenceLevel for a task instance. The value must be between 0.0 and 1.0. To delete the confidenceLevel, specify a value of -1.0.
  */
  public void setConfidenceLevel( @Nonnull final Double confidenceLevel) {
    this.confidenceLevel = confidenceLevel;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link UpdateTaskInstancePayload}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link UpdateTaskInstancePayload} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("UpdateTaskInstancePayload has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link UpdateTaskInstancePayload} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final UpdateTaskInstancePayload updateTaskInstancePayload = (UpdateTaskInstancePayload) o;
    return Objects.equals(this.cloudSdkCustomFields, updateTaskInstancePayload.cloudSdkCustomFields) &&
        Objects.equals(this.context, updateTaskInstancePayload.context) &&
        Objects.equals(this.status, updateTaskInstancePayload.status) &&
        Objects.equals(this.decision, updateTaskInstancePayload.decision) &&
        Objects.equals(this.subject, updateTaskInstancePayload.subject) &&
        Objects.equals(this.description, updateTaskInstancePayload.description) &&
        Objects.equals(this.recipientUsers, updateTaskInstancePayload.recipientUsers) &&
        Objects.equals(this.recipientGroups, updateTaskInstancePayload.recipientGroups) &&
        Objects.equals(this.processor, updateTaskInstancePayload.processor) &&
        Objects.equals(this.dueDate, updateTaskInstancePayload.dueDate) &&
        Objects.equals(this.priority, updateTaskInstancePayload.priority) &&
        Objects.equals(this.confidenceLevel, updateTaskInstancePayload.confidenceLevel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(context, status, decision, subject, description, recipientUsers, recipientGroups, processor, dueDate, priority, confidenceLevel, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class UpdateTaskInstancePayload {\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    decision: ").append(toIndentedString(decision)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    recipientUsers: ").append(toIndentedString(recipientUsers)).append("\n");
    sb.append("    recipientGroups: ").append(toIndentedString(recipientGroups)).append("\n");
    sb.append("    processor: ").append(toIndentedString(processor)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    confidenceLevel: ").append(toIndentedString(confidenceLevel)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

