

/*
 * Workflow
 * This API uses the workflow capability of SAP Build Process Automation. With the API, you can, for example, start new workflow instances and work with tasks.  Note: These APIs are designed for loosely coupled clients. This means:  - If SAP Build Process Automation adds fields to responses, the API version number does not increase. Your client must ignore new fields. - The order of fields in responses and of entries in arrays may change. This applies unless the API provides an explicit means to specify the desired order. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.demo.spa.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * WorkflowInstanceRolesUpdatePayload
 */

// CHECKSTYLE:OFF
public class WorkflowInstanceRolesUpdatePayload 
// CHECKSTYLE:ON
{
  @JsonProperty("viewerUsers")
  private String viewerUsers;

  @JsonProperty("viewerGroups")
  private String viewerGroups;

  @JsonProperty("adminUsers")
  private String adminUsers;

  @JsonProperty("adminGroups")
  private String adminGroups;

  @JsonProperty("contextViewerUsers")
  private String contextViewerUsers;

  @JsonProperty("contextViewerGroups")
  private String contextViewerGroups;

  @JsonProperty("contextAdminUsers")
  private String contextAdminUsers;

  @JsonProperty("contextAdminGroups")
  private String contextAdminGroups;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the viewerUsers of this {@link WorkflowInstanceRolesUpdatePayload} instance and return the same instance.
   *
   * @param viewerUsers  The users that should be assigned to the viewer role, as a comma-separated list. Specify at most 100 user IDs. The ID of a user can be at most 255 characters long.
   * @return The same instance of this {@link WorkflowInstanceRolesUpdatePayload} class
   */
   @Nonnull public WorkflowInstanceRolesUpdatePayload viewerUsers(@Nonnull final String viewerUsers) {
    this.viewerUsers = viewerUsers;
    return this;
  }

   /**
   * The users that should be assigned to the viewer role, as a comma-separated list. Specify at most 100 user IDs. The ID of a user can be at most 255 characters long.
   * @return viewerUsers  The viewerUsers of this {@link WorkflowInstanceRolesUpdatePayload} instance.
  **/
  @Nonnull public String getViewerUsers() {
    return viewerUsers;
  }

  /**
  * Set the viewerUsers of this {@link WorkflowInstanceRolesUpdatePayload} instance.
  *
  * @param viewerUsers  The users that should be assigned to the viewer role, as a comma-separated list. Specify at most 100 user IDs. The ID of a user can be at most 255 characters long.
  */
  public void setViewerUsers( @Nonnull final String viewerUsers) {
    this.viewerUsers = viewerUsers;
  }

   /**
   * Set the viewerGroups of this {@link WorkflowInstanceRolesUpdatePayload} instance and return the same instance.
   *
   * @param viewerGroups  The groups that should be assigned to the viewer role, as a comma-separated list. Specify at most 100 group IDs. The ID of a group can be at most 255 characters long.
   * @return The same instance of this {@link WorkflowInstanceRolesUpdatePayload} class
   */
   @Nonnull public WorkflowInstanceRolesUpdatePayload viewerGroups(@Nonnull final String viewerGroups) {
    this.viewerGroups = viewerGroups;
    return this;
  }

   /**
   * The groups that should be assigned to the viewer role, as a comma-separated list. Specify at most 100 group IDs. The ID of a group can be at most 255 characters long.
   * @return viewerGroups  The viewerGroups of this {@link WorkflowInstanceRolesUpdatePayload} instance.
  **/
  @Nonnull public String getViewerGroups() {
    return viewerGroups;
  }

  /**
  * Set the viewerGroups of this {@link WorkflowInstanceRolesUpdatePayload} instance.
  *
  * @param viewerGroups  The groups that should be assigned to the viewer role, as a comma-separated list. Specify at most 100 group IDs. The ID of a group can be at most 255 characters long.
  */
  public void setViewerGroups( @Nonnull final String viewerGroups) {
    this.viewerGroups = viewerGroups;
  }

   /**
   * Set the adminUsers of this {@link WorkflowInstanceRolesUpdatePayload} instance and return the same instance.
   *
   * @param adminUsers  The users that should be assigned to the admin role, as a comma-separated list. Specify at most 100 user IDs. The ID of a user can be at most 255 characters long.
   * @return The same instance of this {@link WorkflowInstanceRolesUpdatePayload} class
   */
   @Nonnull public WorkflowInstanceRolesUpdatePayload adminUsers(@Nonnull final String adminUsers) {
    this.adminUsers = adminUsers;
    return this;
  }

   /**
   * The users that should be assigned to the admin role, as a comma-separated list. Specify at most 100 user IDs. The ID of a user can be at most 255 characters long.
   * @return adminUsers  The adminUsers of this {@link WorkflowInstanceRolesUpdatePayload} instance.
  **/
  @Nonnull public String getAdminUsers() {
    return adminUsers;
  }

  /**
  * Set the adminUsers of this {@link WorkflowInstanceRolesUpdatePayload} instance.
  *
  * @param adminUsers  The users that should be assigned to the admin role, as a comma-separated list. Specify at most 100 user IDs. The ID of a user can be at most 255 characters long.
  */
  public void setAdminUsers( @Nonnull final String adminUsers) {
    this.adminUsers = adminUsers;
  }

   /**
   * Set the adminGroups of this {@link WorkflowInstanceRolesUpdatePayload} instance and return the same instance.
   *
   * @param adminGroups  The groups that should be assigned to the admin role, as a comma-separated list. Specify at most 100 group IDs. The ID of a group can be at most 255 characters long.
   * @return The same instance of this {@link WorkflowInstanceRolesUpdatePayload} class
   */
   @Nonnull public WorkflowInstanceRolesUpdatePayload adminGroups(@Nonnull final String adminGroups) {
    this.adminGroups = adminGroups;
    return this;
  }

   /**
   * The groups that should be assigned to the admin role, as a comma-separated list. Specify at most 100 group IDs. The ID of a group can be at most 255 characters long.
   * @return adminGroups  The adminGroups of this {@link WorkflowInstanceRolesUpdatePayload} instance.
  **/
  @Nonnull public String getAdminGroups() {
    return adminGroups;
  }

  /**
  * Set the adminGroups of this {@link WorkflowInstanceRolesUpdatePayload} instance.
  *
  * @param adminGroups  The groups that should be assigned to the admin role, as a comma-separated list. Specify at most 100 group IDs. The ID of a group can be at most 255 characters long.
  */
  public void setAdminGroups( @Nonnull final String adminGroups) {
    this.adminGroups = adminGroups;
  }

   /**
   * Set the contextViewerUsers of this {@link WorkflowInstanceRolesUpdatePayload} instance and return the same instance.
   *
   * @param contextViewerUsers  The users that should be assigned to the context viewer role, as a comma-separated list. Specify at most 100 user IDs. The ID of a user can be at most 255 characters long.
   * @return The same instance of this {@link WorkflowInstanceRolesUpdatePayload} class
   */
   @Nonnull public WorkflowInstanceRolesUpdatePayload contextViewerUsers(@Nonnull final String contextViewerUsers) {
    this.contextViewerUsers = contextViewerUsers;
    return this;
  }

   /**
   * The users that should be assigned to the context viewer role, as a comma-separated list. Specify at most 100 user IDs. The ID of a user can be at most 255 characters long.
   * @return contextViewerUsers  The contextViewerUsers of this {@link WorkflowInstanceRolesUpdatePayload} instance.
  **/
  @Nonnull public String getContextViewerUsers() {
    return contextViewerUsers;
  }

  /**
  * Set the contextViewerUsers of this {@link WorkflowInstanceRolesUpdatePayload} instance.
  *
  * @param contextViewerUsers  The users that should be assigned to the context viewer role, as a comma-separated list. Specify at most 100 user IDs. The ID of a user can be at most 255 characters long.
  */
  public void setContextViewerUsers( @Nonnull final String contextViewerUsers) {
    this.contextViewerUsers = contextViewerUsers;
  }

   /**
   * Set the contextViewerGroups of this {@link WorkflowInstanceRolesUpdatePayload} instance and return the same instance.
   *
   * @param contextViewerGroups  The groups that should be assigned to the context viewer role, as a comma-separated list. Specify at most 100 group IDs. The ID of a group can be at most 255 characters long.
   * @return The same instance of this {@link WorkflowInstanceRolesUpdatePayload} class
   */
   @Nonnull public WorkflowInstanceRolesUpdatePayload contextViewerGroups(@Nonnull final String contextViewerGroups) {
    this.contextViewerGroups = contextViewerGroups;
    return this;
  }

   /**
   * The groups that should be assigned to the context viewer role, as a comma-separated list. Specify at most 100 group IDs. The ID of a group can be at most 255 characters long.
   * @return contextViewerGroups  The contextViewerGroups of this {@link WorkflowInstanceRolesUpdatePayload} instance.
  **/
  @Nonnull public String getContextViewerGroups() {
    return contextViewerGroups;
  }

  /**
  * Set the contextViewerGroups of this {@link WorkflowInstanceRolesUpdatePayload} instance.
  *
  * @param contextViewerGroups  The groups that should be assigned to the context viewer role, as a comma-separated list. Specify at most 100 group IDs. The ID of a group can be at most 255 characters long.
  */
  public void setContextViewerGroups( @Nonnull final String contextViewerGroups) {
    this.contextViewerGroups = contextViewerGroups;
  }

   /**
   * Set the contextAdminUsers of this {@link WorkflowInstanceRolesUpdatePayload} instance and return the same instance.
   *
   * @param contextAdminUsers  The users that should be assigned to the context admin role, as a comma-separated list. Specify at most 100 user IDs. The ID of a user can be at most 255 characters long.
   * @return The same instance of this {@link WorkflowInstanceRolesUpdatePayload} class
   */
   @Nonnull public WorkflowInstanceRolesUpdatePayload contextAdminUsers(@Nonnull final String contextAdminUsers) {
    this.contextAdminUsers = contextAdminUsers;
    return this;
  }

   /**
   * The users that should be assigned to the context admin role, as a comma-separated list. Specify at most 100 user IDs. The ID of a user can be at most 255 characters long.
   * @return contextAdminUsers  The contextAdminUsers of this {@link WorkflowInstanceRolesUpdatePayload} instance.
  **/
  @Nonnull public String getContextAdminUsers() {
    return contextAdminUsers;
  }

  /**
  * Set the contextAdminUsers of this {@link WorkflowInstanceRolesUpdatePayload} instance.
  *
  * @param contextAdminUsers  The users that should be assigned to the context admin role, as a comma-separated list. Specify at most 100 user IDs. The ID of a user can be at most 255 characters long.
  */
  public void setContextAdminUsers( @Nonnull final String contextAdminUsers) {
    this.contextAdminUsers = contextAdminUsers;
  }

   /**
   * Set the contextAdminGroups of this {@link WorkflowInstanceRolesUpdatePayload} instance and return the same instance.
   *
   * @param contextAdminGroups  The groups that should be assigned to the context admin role, as a comma-separated list. Specify at most 100 group IDs. The ID of a group can be at most 255 characters long.
   * @return The same instance of this {@link WorkflowInstanceRolesUpdatePayload} class
   */
   @Nonnull public WorkflowInstanceRolesUpdatePayload contextAdminGroups(@Nonnull final String contextAdminGroups) {
    this.contextAdminGroups = contextAdminGroups;
    return this;
  }

   /**
   * The groups that should be assigned to the context admin role, as a comma-separated list. Specify at most 100 group IDs. The ID of a group can be at most 255 characters long.
   * @return contextAdminGroups  The contextAdminGroups of this {@link WorkflowInstanceRolesUpdatePayload} instance.
  **/
  @Nonnull public String getContextAdminGroups() {
    return contextAdminGroups;
  }

  /**
  * Set the contextAdminGroups of this {@link WorkflowInstanceRolesUpdatePayload} instance.
  *
  * @param contextAdminGroups  The groups that should be assigned to the context admin role, as a comma-separated list. Specify at most 100 group IDs. The ID of a group can be at most 255 characters long.
  */
  public void setContextAdminGroups( @Nonnull final String contextAdminGroups) {
    this.contextAdminGroups = contextAdminGroups;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link WorkflowInstanceRolesUpdatePayload}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link WorkflowInstanceRolesUpdatePayload} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("WorkflowInstanceRolesUpdatePayload has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link WorkflowInstanceRolesUpdatePayload} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final WorkflowInstanceRolesUpdatePayload workflowInstanceRolesUpdatePayload = (WorkflowInstanceRolesUpdatePayload) o;
    return Objects.equals(this.cloudSdkCustomFields, workflowInstanceRolesUpdatePayload.cloudSdkCustomFields) &&
        Objects.equals(this.viewerUsers, workflowInstanceRolesUpdatePayload.viewerUsers) &&
        Objects.equals(this.viewerGroups, workflowInstanceRolesUpdatePayload.viewerGroups) &&
        Objects.equals(this.adminUsers, workflowInstanceRolesUpdatePayload.adminUsers) &&
        Objects.equals(this.adminGroups, workflowInstanceRolesUpdatePayload.adminGroups) &&
        Objects.equals(this.contextViewerUsers, workflowInstanceRolesUpdatePayload.contextViewerUsers) &&
        Objects.equals(this.contextViewerGroups, workflowInstanceRolesUpdatePayload.contextViewerGroups) &&
        Objects.equals(this.contextAdminUsers, workflowInstanceRolesUpdatePayload.contextAdminUsers) &&
        Objects.equals(this.contextAdminGroups, workflowInstanceRolesUpdatePayload.contextAdminGroups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(viewerUsers, viewerGroups, adminUsers, adminGroups, contextViewerUsers, contextViewerGroups, contextAdminUsers, contextAdminGroups, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowInstanceRolesUpdatePayload {\n");
    sb.append("    viewerUsers: ").append(toIndentedString(viewerUsers)).append("\n");
    sb.append("    viewerGroups: ").append(toIndentedString(viewerGroups)).append("\n");
    sb.append("    adminUsers: ").append(toIndentedString(adminUsers)).append("\n");
    sb.append("    adminGroups: ").append(toIndentedString(adminGroups)).append("\n");
    sb.append("    contextViewerUsers: ").append(toIndentedString(contextViewerUsers)).append("\n");
    sb.append("    contextViewerGroups: ").append(toIndentedString(contextViewerGroups)).append("\n");
    sb.append("    contextAdminUsers: ").append(toIndentedString(contextAdminUsers)).append("\n");
    sb.append("    contextAdminGroups: ").append(toIndentedString(contextAdminGroups)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

