

/*
 * Workflow
 * This API uses the workflow capability of SAP Build Process Automation. With the API, you can, for example, start new workflow instances and work with tasks.  Note: These APIs are designed for loosely coupled clients. This means:  - If SAP Build Process Automation adds fields to responses, the API version number does not increase. Your client must ignore new fields. - The order of fields in responses and of entries in arrays may change. This applies unless the API provides an explicit means to specify the desired order. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.demo.spa.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import customer.demo.spa.model.WorkflowInstanceExecutionLogActionTask;
import customer.demo.spa.model.WorkflowInstanceExecutionLogChanges;
import customer.demo.spa.model.WorkflowInstanceExecutionLogError;
import customer.demo.spa.model.WorkflowInstanceExecutionLogRecipients;
import customer.demo.spa.model.WorkflowInstanceExecutionLogRestEndpoint;
import customer.demo.spa.model.WorkflowInstanceExecutionLogRuleService;
import java.time.OffsetDateTime;
import java.util.LinkedHashSet;
import java.util.Set;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * WorkflowInstanceExecutionLog
 */

// CHECKSTYLE:OFF
public class WorkflowInstanceExecutionLog 
// CHECKSTYLE:ON
{
  @JsonProperty("id")
  private String id;

  /**
   * The execution log entry type.
   */
  public enum TypeEnum {
    /**
    * The WORKFLOW_STARTED option of this WorkflowInstanceExecutionLog
    */
    WORKFLOW_STARTED("WORKFLOW_STARTED"),
    
    /**
    * The WORKFLOW_COMPLETED option of this WorkflowInstanceExecutionLog
    */
    WORKFLOW_COMPLETED("WORKFLOW_COMPLETED"),
    
    /**
    * The WORKFLOW_CANCELED option of this WorkflowInstanceExecutionLog
    */
    WORKFLOW_CANCELED("WORKFLOW_CANCELED"),
    
    /**
    * The WORKFLOW_CONTINUED option of this WorkflowInstanceExecutionLog
    */
    WORKFLOW_CONTINUED("WORKFLOW_CONTINUED"),
    
    /**
    * The WORKFLOW_SUSPENDED option of this WorkflowInstanceExecutionLog
    */
    WORKFLOW_SUSPENDED("WORKFLOW_SUSPENDED"),
    
    /**
    * The WORKFLOW_CONTEXT_OVERWRITTEN_BY_ADMIN option of this WorkflowInstanceExecutionLog
    */
    WORKFLOW_CONTEXT_OVERWRITTEN_BY_ADMIN("WORKFLOW_CONTEXT_OVERWRITTEN_BY_ADMIN"),
    
    /**
    * The WORKFLOW_CONTEXT_PATCHED_BY_ADMIN option of this WorkflowInstanceExecutionLog
    */
    WORKFLOW_CONTEXT_PATCHED_BY_ADMIN("WORKFLOW_CONTEXT_PATCHED_BY_ADMIN"),
    
    /**
    * The WORKFLOW_ROLES_PATCHED_BY_ADMIN option of this WorkflowInstanceExecutionLog
    */
    WORKFLOW_ROLES_PATCHED_BY_ADMIN("WORKFLOW_ROLES_PATCHED_BY_ADMIN"),
    
    /**
    * The WORKFLOW_RESUMED option of this WorkflowInstanceExecutionLog
    */
    WORKFLOW_RESUMED("WORKFLOW_RESUMED"),
    
    /**
    * The USERTASK_CREATED option of this WorkflowInstanceExecutionLog
    */
    USERTASK_CREATED("USERTASK_CREATED"),
    
    /**
    * The USERTASK_CLAIMED option of this WorkflowInstanceExecutionLog
    */
    USERTASK_CLAIMED("USERTASK_CLAIMED"),
    
    /**
    * The USERTASK_RELEASED option of this WorkflowInstanceExecutionLog
    */
    USERTASK_RELEASED("USERTASK_RELEASED"),
    
    /**
    * The USERTASK_COMPLETED option of this WorkflowInstanceExecutionLog
    */
    USERTASK_COMPLETED("USERTASK_COMPLETED"),
    
    /**
    * The USERTASK_FAILED option of this WorkflowInstanceExecutionLog
    */
    USERTASK_FAILED("USERTASK_FAILED"),
    
    /**
    * The USERTASK_PATCHED_BY_ADMIN option of this WorkflowInstanceExecutionLog
    */
    USERTASK_PATCHED_BY_ADMIN("USERTASK_PATCHED_BY_ADMIN"),
    
    /**
    * The USERTASK_CANCELED_BY_BOUNDARY_EVENT option of this WorkflowInstanceExecutionLog
    */
    USERTASK_CANCELED_BY_BOUNDARY_EVENT("USERTASK_CANCELED_BY_BOUNDARY_EVENT"),
    
    /**
    * The SERVICETASK_CREATED option of this WorkflowInstanceExecutionLog
    */
    SERVICETASK_CREATED("SERVICETASK_CREATED"),
    
    /**
    * The SERVICETASK_COMPLETED option of this WorkflowInstanceExecutionLog
    */
    SERVICETASK_COMPLETED("SERVICETASK_COMPLETED"),
    
    /**
    * The SERVICETASK_FAILED option of this WorkflowInstanceExecutionLog
    */
    SERVICETASK_FAILED("SERVICETASK_FAILED"),
    
    /**
    * The SCRIPTTASK_CREATED option of this WorkflowInstanceExecutionLog
    */
    SCRIPTTASK_CREATED("SCRIPTTASK_CREATED"),
    
    /**
    * The SCRIPTTASK_COMPLETED option of this WorkflowInstanceExecutionLog
    */
    SCRIPTTASK_COMPLETED("SCRIPTTASK_COMPLETED"),
    
    /**
    * The SCRIPTTASK_FAILED option of this WorkflowInstanceExecutionLog
    */
    SCRIPTTASK_FAILED("SCRIPTTASK_FAILED"),
    
    /**
    * The INTERMEDIATE_TIMER_EVENT_REACHED option of this WorkflowInstanceExecutionLog
    */
    INTERMEDIATE_TIMER_EVENT_REACHED("INTERMEDIATE_TIMER_EVENT_REACHED"),
    
    /**
    * The INTERMEDIATE_TIMER_EVENT_TRIGGERED option of this WorkflowInstanceExecutionLog
    */
    INTERMEDIATE_TIMER_EVENT_TRIGGERED("INTERMEDIATE_TIMER_EVENT_TRIGGERED"),
    
    /**
    * The INTERMEDIATE_TIMER_EVENT_FAILED option of this WorkflowInstanceExecutionLog
    */
    INTERMEDIATE_TIMER_EVENT_FAILED("INTERMEDIATE_TIMER_EVENT_FAILED"),
    
    /**
    * The INTERMEDIATE_MESSAGE_EVENT_REACHED option of this WorkflowInstanceExecutionLog
    */
    INTERMEDIATE_MESSAGE_EVENT_REACHED("INTERMEDIATE_MESSAGE_EVENT_REACHED"),
    
    /**
    * The INTERMEDIATE_MESSAGE_EVENT_TRIGGERED option of this WorkflowInstanceExecutionLog
    */
    INTERMEDIATE_MESSAGE_EVENT_TRIGGERED("INTERMEDIATE_MESSAGE_EVENT_TRIGGERED"),
    
    /**
    * The NONCANCELING_BOUNDARY_TIMER_EVENT_TRIGGERED option of this WorkflowInstanceExecutionLog
    */
    NONCANCELING_BOUNDARY_TIMER_EVENT_TRIGGERED("NONCANCELING_BOUNDARY_TIMER_EVENT_TRIGGERED"),
    
    /**
    * The CANCELING_BOUNDARY_TIMER_EVENT_TRIGGERED option of this WorkflowInstanceExecutionLog
    */
    CANCELING_BOUNDARY_TIMER_EVENT_TRIGGERED("CANCELING_BOUNDARY_TIMER_EVENT_TRIGGERED"),
    
    /**
    * The MAILTASK_CREATED option of this WorkflowInstanceExecutionLog
    */
    MAILTASK_CREATED("MAILTASK_CREATED"),
    
    /**
    * The MAILTASK_COMPLETED option of this WorkflowInstanceExecutionLog
    */
    MAILTASK_COMPLETED("MAILTASK_COMPLETED"),
    
    /**
    * The MAILTASK_FAILED option of this WorkflowInstanceExecutionLog
    */
    MAILTASK_FAILED("MAILTASK_FAILED"),
    
    /**
    * The EXCLUSIVE_GATEWAY_REACHED option of this WorkflowInstanceExecutionLog
    */
    EXCLUSIVE_GATEWAY_REACHED("EXCLUSIVE_GATEWAY_REACHED"),
    
    /**
    * The EXCLUSIVE_GATEWAY_FAILED option of this WorkflowInstanceExecutionLog
    */
    EXCLUSIVE_GATEWAY_FAILED("EXCLUSIVE_GATEWAY_FAILED"),
    
    /**
    * The PARALLEL_GATEWAY_REACHED option of this WorkflowInstanceExecutionLog
    */
    PARALLEL_GATEWAY_REACHED("PARALLEL_GATEWAY_REACHED"),
    
    /**
    * The PARALLEL_GATEWAY_FAILED option of this WorkflowInstanceExecutionLog
    */
    PARALLEL_GATEWAY_FAILED("PARALLEL_GATEWAY_FAILED"),
    
    /**
    * The AUTOMATIONTASK_CREATED option of this WorkflowInstanceExecutionLog
    */
    AUTOMATIONTASK_CREATED("AUTOMATIONTASK_CREATED"),
    
    /**
    * The AUTOMATIONTASK_COMPLETED option of this WorkflowInstanceExecutionLog
    */
    AUTOMATIONTASK_COMPLETED("AUTOMATIONTASK_COMPLETED"),
    
    /**
    * The AUTOMATIONTASK_FAILED option of this WorkflowInstanceExecutionLog
    */
    AUTOMATIONTASK_FAILED("AUTOMATIONTASK_FAILED"),
    
    /**
    * The ACTIONTASK_CREATED option of this WorkflowInstanceExecutionLog
    */
    ACTIONTASK_CREATED("ACTIONTASK_CREATED"),
    
    /**
    * The ACTIONTASK_COMPLETED option of this WorkflowInstanceExecutionLog
    */
    ACTIONTASK_COMPLETED("ACTIONTASK_COMPLETED"),
    
    /**
    * The ACTIONTASK_FAILED option of this WorkflowInstanceExecutionLog
    */
    ACTIONTASK_FAILED("ACTIONTASK_FAILED"),
    
    /**
    * The RULETASK_CREATED option of this WorkflowInstanceExecutionLog
    */
    RULETASK_CREATED("RULETASK_CREATED"),
    
    /**
    * The RULETASK_COMPLETED option of this WorkflowInstanceExecutionLog
    */
    RULETASK_COMPLETED("RULETASK_COMPLETED"),
    
    /**
    * The RULETASK_FAILED option of this WorkflowInstanceExecutionLog
    */
    RULETASK_FAILED("RULETASK_FAILED"),
    
    /**
    * The INTERMEDIATE_ESCALATION_EVENT_EMITTED option of this WorkflowInstanceExecutionLog
    */
    INTERMEDIATE_ESCALATION_EVENT_EMITTED("INTERMEDIATE_ESCALATION_EVENT_EMITTED"),
    
    /**
    * The CANCELING_BOUNDARY_ESCALATION_EVENT_TRIGGERED option of this WorkflowInstanceExecutionLog
    */
    CANCELING_BOUNDARY_ESCALATION_EVENT_TRIGGERED("CANCELING_BOUNDARY_ESCALATION_EVENT_TRIGGERED"),
    
    /**
    * The NONCANCELING_BOUNDARY_ESCALATION_EVENT_TRIGGERED option of this WorkflowInstanceExecutionLog
    */
    NONCANCELING_BOUNDARY_ESCALATION_EVENT_TRIGGERED("NONCANCELING_BOUNDARY_ESCALATION_EVENT_TRIGGERED");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type WorkflowInstanceExecutionLog
    */
    @JsonCreator
    @Nonnull public static TypeEnum fromValue(@Nonnull final String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("type")
  private TypeEnum type;

  @JsonProperty("timestamp")
  private OffsetDateTime timestamp;

  @JsonProperty("referenceInstanceId")
  private String referenceInstanceId;

  @JsonProperty("activityId")
  private String activityId;

  @JsonProperty("parentInstanceId")
  private String parentInstanceId;

  @JsonProperty("rootInstanceId")
  private String rootInstanceId;

  @JsonProperty("subject")
  private String subject;

  @JsonProperty("userId")
  private String userId;

  @JsonProperty("escalationCode")
  private String escalationCode;

  @JsonProperty("ruleService")
  private WorkflowInstanceExecutionLogRuleService ruleService;

  @JsonProperty("actionTask")
  private WorkflowInstanceExecutionLogActionTask actionTask;

  @JsonProperty("error")
  private WorkflowInstanceExecutionLogError error;

  @JsonProperty("recipientUsers")
  private Set<String> recipientUsers = new LinkedHashSet<>();

  @JsonProperty("recipientGroups")
  private Set<String> recipientGroups = new LinkedHashSet<>();

  @JsonProperty("initiatorId")
  private String initiatorId;

  @JsonProperty("restEndpoint")
  private WorkflowInstanceExecutionLogRestEndpoint restEndpoint;

  @JsonProperty("retriesRemaining")
  private Integer retriesRemaining;

  @JsonProperty("taskId")
  private String taskId;

  @JsonProperty("changes")
  private WorkflowInstanceExecutionLogChanges changes;

  @JsonProperty("recipients")
  private WorkflowInstanceExecutionLogRecipients recipients;

  @JsonProperty("sendDisabled")
  private Boolean sendDisabled = false;

  @JsonProperty("propagatedPrincipal")
  private String propagatedPrincipal;

  @JsonProperty("activityName")
  private String activityName;

  @JsonProperty("cause")
  private String cause;

  @JsonProperty("boundaryEventName")
  private String boundaryEventName;

  @JsonProperty("destinationSubdomain")
  private String destinationSubdomain;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the id of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param id  The ID of the execution log entry.
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog id(@Nonnull final String id) {
    this.id = id;
    return this;
  }

   /**
   * The ID of the execution log entry.
   * @return id  The id of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public String getId() {
    return id;
  }

  /**
  * Set the id of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param id  The ID of the execution log entry.
  */
  public void setId( @Nonnull final String id) {
    this.id = id;
  }

   /**
   * Set the type of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param type  The execution log entry type.
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog type(@Nonnull final TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * The execution log entry type.
   * @return type  The type of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public TypeEnum getType() {
    return type;
  }

  /**
  * Set the type of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param type  The execution log entry type.
  */
  public void setType( @Nonnull final TypeEnum type) {
    this.type = type;
  }

   /**
   * Set the timestamp of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param timestamp  The time the execution log entry was created.
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog timestamp(@Nonnull final OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * The time the execution log entry was created.
   * @return timestamp  The timestamp of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  /**
  * Set the timestamp of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param timestamp  The time the execution log entry was created.
  */
  public void setTimestamp( @Nonnull final OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }

   /**
   * Set the referenceInstanceId of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param referenceInstanceId  An ID that groups events together by their activity and their token of execution in the workflow. For example, all events relating to the same script task (started, failed, completed) would have the same referenceInstanceId. 
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog referenceInstanceId(@Nonnull final String referenceInstanceId) {
    this.referenceInstanceId = referenceInstanceId;
    return this;
  }

   /**
   * An ID that groups events together by their activity and their token of execution in the workflow. For example, all events relating to the same script task (started, failed, completed) would have the same referenceInstanceId. 
   * @return referenceInstanceId  The referenceInstanceId of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public String getReferenceInstanceId() {
    return referenceInstanceId;
  }

  /**
  * Set the referenceInstanceId of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param referenceInstanceId  An ID that groups events together by their activity and their token of execution in the workflow. For example, all events relating to the same script task (started, failed, completed) would have the same referenceInstanceId. 
  */
  public void setReferenceInstanceId( @Nonnull final String referenceInstanceId) {
    this.referenceInstanceId = referenceInstanceId;
  }

   /**
   * Set the activityId of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param activityId  The ID of the model element. The ID is at most 255 characters long.
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog activityId(@Nonnull final String activityId) {
    this.activityId = activityId;
    return this;
  }

   /**
   * The ID of the model element. The ID is at most 255 characters long.
   * @return activityId  The activityId of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public String getActivityId() {
    return activityId;
  }

  /**
  * Set the activityId of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param activityId  The ID of the model element. The ID is at most 255 characters long.
  */
  public void setActivityId( @Nonnull final String activityId) {
    this.activityId = activityId;
  }

   /**
   * Set the parentInstanceId of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param parentInstanceId  The ID of the parent workflow instance. The ID is at most 64 characters long.
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog parentInstanceId(@Nonnull final String parentInstanceId) {
    this.parentInstanceId = parentInstanceId;
    return this;
  }

   /**
   * The ID of the parent workflow instance. The ID is at most 64 characters long.
   * @return parentInstanceId  The parentInstanceId of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public String getParentInstanceId() {
    return parentInstanceId;
  }

  /**
  * Set the parentInstanceId of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param parentInstanceId  The ID of the parent workflow instance. The ID is at most 64 characters long.
  */
  public void setParentInstanceId( @Nonnull final String parentInstanceId) {
    this.parentInstanceId = parentInstanceId;
  }

   /**
   * Set the rootInstanceId of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param rootInstanceId  The ID of the root workflow instance. The ID is at most 64 characters long.
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog rootInstanceId(@Nonnull final String rootInstanceId) {
    this.rootInstanceId = rootInstanceId;
    return this;
  }

   /**
   * The ID of the root workflow instance. The ID is at most 64 characters long.
   * @return rootInstanceId  The rootInstanceId of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public String getRootInstanceId() {
    return rootInstanceId;
  }

  /**
  * Set the rootInstanceId of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param rootInstanceId  The ID of the root workflow instance. The ID is at most 64 characters long.
  */
  public void setRootInstanceId( @Nonnull final String rootInstanceId) {
    this.rootInstanceId = rootInstanceId;
  }

   /**
   * Set the subject of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param subject  The name of the model element or the subject of the user task. The name/subject is at most 255 characters long.
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog subject(@Nonnull final String subject) {
    this.subject = subject;
    return this;
  }

   /**
   * The name of the model element or the subject of the user task. The name/subject is at most 255 characters long.
   * @return subject  The subject of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public String getSubject() {
    return subject;
  }

  /**
  * Set the subject of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param subject  The name of the model element or the subject of the user task. The name/subject is at most 255 characters long.
  */
  public void setSubject( @Nonnull final String subject) {
    this.subject = subject;
  }

   /**
   * Set the userId of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param userId  The user who executed the action. The user ID is at most 255 characters long.
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog userId(@Nonnull final String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * The user who executed the action. The user ID is at most 255 characters long.
   * @return userId  The userId of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public String getUserId() {
    return userId;
  }

  /**
  * Set the userId of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param userId  The user who executed the action. The user ID is at most 255 characters long.
  */
  public void setUserId( @Nonnull final String userId) {
    this.userId = userId;
  }

   /**
   * Set the escalationCode of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param escalationCode  The code of the escalation emitted.
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog escalationCode(@Nonnull final String escalationCode) {
    this.escalationCode = escalationCode;
    return this;
  }

   /**
   * The code of the escalation emitted.
   * @return escalationCode  The escalationCode of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public String getEscalationCode() {
    return escalationCode;
  }

  /**
  * Set the escalationCode of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param escalationCode  The code of the escalation emitted.
  */
  public void setEscalationCode( @Nonnull final String escalationCode) {
    this.escalationCode = escalationCode;
  }

   /**
   * Set the ruleService of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param ruleService  The ruleService of this {@link WorkflowInstanceExecutionLog}
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog ruleService(@Nonnull final WorkflowInstanceExecutionLogRuleService ruleService) {
    this.ruleService = ruleService;
    return this;
  }

   /**
   * Get ruleService
   * @return ruleService  The ruleService of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public WorkflowInstanceExecutionLogRuleService getRuleService() {
    return ruleService;
  }

  /**
  * Set the ruleService of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param ruleService  The ruleService of this {@link WorkflowInstanceExecutionLog}
  */
  public void setRuleService( @Nonnull final WorkflowInstanceExecutionLogRuleService ruleService) {
    this.ruleService = ruleService;
  }

   /**
   * Set the actionTask of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param actionTask  The actionTask of this {@link WorkflowInstanceExecutionLog}
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog actionTask(@Nonnull final WorkflowInstanceExecutionLogActionTask actionTask) {
    this.actionTask = actionTask;
    return this;
  }

   /**
   * Get actionTask
   * @return actionTask  The actionTask of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public WorkflowInstanceExecutionLogActionTask getActionTask() {
    return actionTask;
  }

  /**
  * Set the actionTask of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param actionTask  The actionTask of this {@link WorkflowInstanceExecutionLog}
  */
  public void setActionTask( @Nonnull final WorkflowInstanceExecutionLogActionTask actionTask) {
    this.actionTask = actionTask;
  }

   /**
   * Set the error of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param error  The error of this {@link WorkflowInstanceExecutionLog}
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog error(@Nonnull final WorkflowInstanceExecutionLogError error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error  The error of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public WorkflowInstanceExecutionLogError getError() {
    return error;
  }

  /**
  * Set the error of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param error  The error of this {@link WorkflowInstanceExecutionLog}
  */
  public void setError( @Nonnull final WorkflowInstanceExecutionLogError error) {
    this.error = error;
  }

   /**
   * Set the recipientUsers of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param recipientUsers  The recipient users of a user task.
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog recipientUsers(@Nonnull final Set<String> recipientUsers) {
    this.recipientUsers = recipientUsers;
    return this;
  }
  /**
  * Add one recipientUsers instance to this {@link WorkflowInstanceExecutionLog}.
  * @param recipientUsersItem The recipientUsers that should be added
  * @return The same instance of type {@link WorkflowInstanceExecutionLog}
  */
  @Nonnull public WorkflowInstanceExecutionLog addrecipientUsersItem( @Nonnull final String recipientUsersItem) {
    if (this.recipientUsers == null) {
      this.recipientUsers = new LinkedHashSet<>();
    }
    this.recipientUsers.add(recipientUsersItem);
    return this;
  }

   /**
   * The recipient users of a user task.
   * @return recipientUsers  The recipientUsers of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public Set<String> getRecipientUsers() {
    return recipientUsers;
  }

  /**
  * Set the recipientUsers of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param recipientUsers  The recipient users of a user task.
  */
  public void setRecipientUsers( @Nonnull final Set<String> recipientUsers) {
    this.recipientUsers = recipientUsers;
  }

   /**
   * Set the recipientGroups of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param recipientGroups  The recipient groups of a user task.
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog recipientGroups(@Nonnull final Set<String> recipientGroups) {
    this.recipientGroups = recipientGroups;
    return this;
  }
  /**
  * Add one recipientGroups instance to this {@link WorkflowInstanceExecutionLog}.
  * @param recipientGroupsItem The recipientGroups that should be added
  * @return The same instance of type {@link WorkflowInstanceExecutionLog}
  */
  @Nonnull public WorkflowInstanceExecutionLog addrecipientGroupsItem( @Nonnull final String recipientGroupsItem) {
    if (this.recipientGroups == null) {
      this.recipientGroups = new LinkedHashSet<>();
    }
    this.recipientGroups.add(recipientGroupsItem);
    return this;
  }

   /**
   * The recipient groups of a user task.
   * @return recipientGroups  The recipientGroups of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public Set<String> getRecipientGroups() {
    return recipientGroups;
  }

  /**
  * Set the recipientGroups of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param recipientGroups  The recipient groups of a user task.
  */
  public void setRecipientGroups( @Nonnull final Set<String> recipientGroups) {
    this.recipientGroups = recipientGroups;
  }

   /**
   * Set the initiatorId of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param initiatorId  The user who started the user task. The user ID is at most 255 characters long.
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog initiatorId(@Nonnull final String initiatorId) {
    this.initiatorId = initiatorId;
    return this;
  }

   /**
   * The user who started the user task. The user ID is at most 255 characters long.
   * @return initiatorId  The initiatorId of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public String getInitiatorId() {
    return initiatorId;
  }

  /**
  * Set the initiatorId of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param initiatorId  The user who started the user task. The user ID is at most 255 characters long.
  */
  public void setInitiatorId( @Nonnull final String initiatorId) {
    this.initiatorId = initiatorId;
  }

   /**
   * Set the restEndpoint of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param restEndpoint  The restEndpoint of this {@link WorkflowInstanceExecutionLog}
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog restEndpoint(@Nonnull final WorkflowInstanceExecutionLogRestEndpoint restEndpoint) {
    this.restEndpoint = restEndpoint;
    return this;
  }

   /**
   * Get restEndpoint
   * @return restEndpoint  The restEndpoint of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public WorkflowInstanceExecutionLogRestEndpoint getRestEndpoint() {
    return restEndpoint;
  }

  /**
  * Set the restEndpoint of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param restEndpoint  The restEndpoint of this {@link WorkflowInstanceExecutionLog}
  */
  public void setRestEndpoint( @Nonnull final WorkflowInstanceExecutionLogRestEndpoint restEndpoint) {
    this.restEndpoint = restEndpoint;
  }

   /**
   * Set the retriesRemaining of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param retriesRemaining  The remaining number of retries. If no retries are left the workflow instance is ERRONEOUS.
   * Minimum: 0
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog retriesRemaining(@Nonnull final Integer retriesRemaining) {
    this.retriesRemaining = retriesRemaining;
    return this;
  }

   /**
   * The remaining number of retries. If no retries are left the workflow instance is ERRONEOUS.
   * minimum: 0
   * @return retriesRemaining  The retriesRemaining of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public Integer getRetriesRemaining() {
    return retriesRemaining;
  }

  /**
  * Set the retriesRemaining of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param retriesRemaining  The remaining number of retries. If no retries are left the workflow instance is ERRONEOUS.
  * Minimum: 0
  */
  public void setRetriesRemaining( @Nonnull final Integer retriesRemaining) {
    this.retriesRemaining = retriesRemaining;
  }

   /**
   * Set the taskId of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param taskId  The ID of the user task. The ID is at least 36 characters long.
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog taskId(@Nonnull final String taskId) {
    this.taskId = taskId;
    return this;
  }

   /**
   * The ID of the user task. The ID is at least 36 characters long.
   * @return taskId  The taskId of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public String getTaskId() {
    return taskId;
  }

  /**
  * Set the taskId of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param taskId  The ID of the user task. The ID is at least 36 characters long.
  */
  public void setTaskId( @Nonnull final String taskId) {
    this.taskId = taskId;
  }

   /**
   * Set the changes of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param changes  The changes of this {@link WorkflowInstanceExecutionLog}
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog changes(@Nonnull final WorkflowInstanceExecutionLogChanges changes) {
    this.changes = changes;
    return this;
  }

   /**
   * Get changes
   * @return changes  The changes of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public WorkflowInstanceExecutionLogChanges getChanges() {
    return changes;
  }

  /**
  * Set the changes of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param changes  The changes of this {@link WorkflowInstanceExecutionLog}
  */
  public void setChanges( @Nonnull final WorkflowInstanceExecutionLogChanges changes) {
    this.changes = changes;
  }

   /**
   * Set the recipients of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param recipients  The recipients of this {@link WorkflowInstanceExecutionLog}
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog recipients(@Nonnull final WorkflowInstanceExecutionLogRecipients recipients) {
    this.recipients = recipients;
    return this;
  }

   /**
   * Get recipients
   * @return recipients  The recipients of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public WorkflowInstanceExecutionLogRecipients getRecipients() {
    return recipients;
  }

  /**
  * Set the recipients of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param recipients  The recipients of this {@link WorkflowInstanceExecutionLog}
  */
  public void setRecipients( @Nonnull final WorkflowInstanceExecutionLogRecipients recipients) {
    this.recipients = recipients;
  }

   /**
   * Set the sendDisabled of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param sendDisabled  Indicates whether the sending of emails is disabled.
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog sendDisabled(@Nonnull final Boolean sendDisabled) {
    this.sendDisabled = sendDisabled;
    return this;
  }

   /**
   * Indicates whether the sending of emails is disabled.
   * @return sendDisabled  The sendDisabled of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public Boolean isSendDisabled() {
    return sendDisabled;
  }

  /**
  * Set the sendDisabled of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param sendDisabled  Indicates whether the sending of emails is disabled.
  */
  public void setSendDisabled( @Nonnull final Boolean sendDisabled) {
    this.sendDisabled = sendDisabled;
  }

   /**
   * Set the propagatedPrincipal of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param propagatedPrincipal  The name of the principal on whose behalf the service task has been executed.
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog propagatedPrincipal(@Nonnull final String propagatedPrincipal) {
    this.propagatedPrincipal = propagatedPrincipal;
    return this;
  }

   /**
   * The name of the principal on whose behalf the service task has been executed.
   * @return propagatedPrincipal  The propagatedPrincipal of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public String getPropagatedPrincipal() {
    return propagatedPrincipal;
  }

  /**
  * Set the propagatedPrincipal of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param propagatedPrincipal  The name of the principal on whose behalf the service task has been executed.
  */
  public void setPropagatedPrincipal( @Nonnull final String propagatedPrincipal) {
    this.propagatedPrincipal = propagatedPrincipal;
  }

   /**
   * Set the activityName of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param activityName  The name of the affected model element. The activity name is at most 255 characters long.
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog activityName(@Nonnull final String activityName) {
    this.activityName = activityName;
    return this;
  }

   /**
   * The name of the affected model element. The activity name is at most 255 characters long.
   * @return activityName  The activityName of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public String getActivityName() {
    return activityName;
  }

  /**
  * Set the activityName of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param activityName  The name of the affected model element. The activity name is at most 255 characters long.
  */
  public void setActivityName( @Nonnull final String activityName) {
    this.activityName = activityName;
  }

   /**
   * Set the cause of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param cause  The activityId of the boundary timer event causing the cancellation of the user task. It is at most 255 characters long.
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog cause(@Nonnull final String cause) {
    this.cause = cause;
    return this;
  }

   /**
   * The activityId of the boundary timer event causing the cancellation of the user task. It is at most 255 characters long.
   * @return cause  The cause of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public String getCause() {
    return cause;
  }

  /**
  * Set the cause of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param cause  The activityId of the boundary timer event causing the cancellation of the user task. It is at most 255 characters long.
  */
  public void setCause( @Nonnull final String cause) {
    this.cause = cause;
  }

   /**
   * Set the boundaryEventName of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param boundaryEventName  The name of the boundary timer event. The name is at most 64 characters long.
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog boundaryEventName(@Nonnull final String boundaryEventName) {
    this.boundaryEventName = boundaryEventName;
    return this;
  }

   /**
   * The name of the boundary timer event. The name is at most 64 characters long.
   * @return boundaryEventName  The boundaryEventName of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public String getBoundaryEventName() {
    return boundaryEventName;
  }

  /**
  * Set the boundaryEventName of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param boundaryEventName  The name of the boundary timer event. The name is at most 64 characters long.
  */
  public void setBoundaryEventName( @Nonnull final String boundaryEventName) {
    this.boundaryEventName = boundaryEventName;
  }

   /**
   * Set the destinationSubdomain of this {@link WorkflowInstanceExecutionLog} instance and return the same instance.
   *
   * @param destinationSubdomain  The subdomain of the account in which the destination was looked up.
   * @return The same instance of this {@link WorkflowInstanceExecutionLog} class
   */
   @Nonnull public WorkflowInstanceExecutionLog destinationSubdomain(@Nonnull final String destinationSubdomain) {
    this.destinationSubdomain = destinationSubdomain;
    return this;
  }

   /**
   * The subdomain of the account in which the destination was looked up.
   * @return destinationSubdomain  The destinationSubdomain of this {@link WorkflowInstanceExecutionLog} instance.
  **/
  @Nonnull public String getDestinationSubdomain() {
    return destinationSubdomain;
  }

  /**
  * Set the destinationSubdomain of this {@link WorkflowInstanceExecutionLog} instance.
  *
  * @param destinationSubdomain  The subdomain of the account in which the destination was looked up.
  */
  public void setDestinationSubdomain( @Nonnull final String destinationSubdomain) {
    this.destinationSubdomain = destinationSubdomain;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link WorkflowInstanceExecutionLog}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link WorkflowInstanceExecutionLog} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("WorkflowInstanceExecutionLog has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link WorkflowInstanceExecutionLog} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final WorkflowInstanceExecutionLog workflowInstanceExecutionLog = (WorkflowInstanceExecutionLog) o;
    return Objects.equals(this.cloudSdkCustomFields, workflowInstanceExecutionLog.cloudSdkCustomFields) &&
        Objects.equals(this.id, workflowInstanceExecutionLog.id) &&
        Objects.equals(this.type, workflowInstanceExecutionLog.type) &&
        Objects.equals(this.timestamp, workflowInstanceExecutionLog.timestamp) &&
        Objects.equals(this.referenceInstanceId, workflowInstanceExecutionLog.referenceInstanceId) &&
        Objects.equals(this.activityId, workflowInstanceExecutionLog.activityId) &&
        Objects.equals(this.parentInstanceId, workflowInstanceExecutionLog.parentInstanceId) &&
        Objects.equals(this.rootInstanceId, workflowInstanceExecutionLog.rootInstanceId) &&
        Objects.equals(this.subject, workflowInstanceExecutionLog.subject) &&
        Objects.equals(this.userId, workflowInstanceExecutionLog.userId) &&
        Objects.equals(this.escalationCode, workflowInstanceExecutionLog.escalationCode) &&
        Objects.equals(this.ruleService, workflowInstanceExecutionLog.ruleService) &&
        Objects.equals(this.actionTask, workflowInstanceExecutionLog.actionTask) &&
        Objects.equals(this.error, workflowInstanceExecutionLog.error) &&
        Objects.equals(this.recipientUsers, workflowInstanceExecutionLog.recipientUsers) &&
        Objects.equals(this.recipientGroups, workflowInstanceExecutionLog.recipientGroups) &&
        Objects.equals(this.initiatorId, workflowInstanceExecutionLog.initiatorId) &&
        Objects.equals(this.restEndpoint, workflowInstanceExecutionLog.restEndpoint) &&
        Objects.equals(this.retriesRemaining, workflowInstanceExecutionLog.retriesRemaining) &&
        Objects.equals(this.taskId, workflowInstanceExecutionLog.taskId) &&
        Objects.equals(this.changes, workflowInstanceExecutionLog.changes) &&
        Objects.equals(this.recipients, workflowInstanceExecutionLog.recipients) &&
        Objects.equals(this.sendDisabled, workflowInstanceExecutionLog.sendDisabled) &&
        Objects.equals(this.propagatedPrincipal, workflowInstanceExecutionLog.propagatedPrincipal) &&
        Objects.equals(this.activityName, workflowInstanceExecutionLog.activityName) &&
        Objects.equals(this.cause, workflowInstanceExecutionLog.cause) &&
        Objects.equals(this.boundaryEventName, workflowInstanceExecutionLog.boundaryEventName) &&
        Objects.equals(this.destinationSubdomain, workflowInstanceExecutionLog.destinationSubdomain);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, timestamp, referenceInstanceId, activityId, parentInstanceId, rootInstanceId, subject, userId, escalationCode, ruleService, actionTask, error, recipientUsers, recipientGroups, initiatorId, restEndpoint, retriesRemaining, taskId, changes, recipients, sendDisabled, propagatedPrincipal, activityName, cause, boundaryEventName, destinationSubdomain, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowInstanceExecutionLog {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    referenceInstanceId: ").append(toIndentedString(referenceInstanceId)).append("\n");
    sb.append("    activityId: ").append(toIndentedString(activityId)).append("\n");
    sb.append("    parentInstanceId: ").append(toIndentedString(parentInstanceId)).append("\n");
    sb.append("    rootInstanceId: ").append(toIndentedString(rootInstanceId)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    escalationCode: ").append(toIndentedString(escalationCode)).append("\n");
    sb.append("    ruleService: ").append(toIndentedString(ruleService)).append("\n");
    sb.append("    actionTask: ").append(toIndentedString(actionTask)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    recipientUsers: ").append(toIndentedString(recipientUsers)).append("\n");
    sb.append("    recipientGroups: ").append(toIndentedString(recipientGroups)).append("\n");
    sb.append("    initiatorId: ").append(toIndentedString(initiatorId)).append("\n");
    sb.append("    restEndpoint: ").append(toIndentedString(restEndpoint)).append("\n");
    sb.append("    retriesRemaining: ").append(toIndentedString(retriesRemaining)).append("\n");
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    changes: ").append(toIndentedString(changes)).append("\n");
    sb.append("    recipients: ").append(toIndentedString(recipients)).append("\n");
    sb.append("    sendDisabled: ").append(toIndentedString(sendDisabled)).append("\n");
    sb.append("    propagatedPrincipal: ").append(toIndentedString(propagatedPrincipal)).append("\n");
    sb.append("    activityName: ").append(toIndentedString(activityName)).append("\n");
    sb.append("    cause: ").append(toIndentedString(cause)).append("\n");
    sb.append("    boundaryEventName: ").append(toIndentedString(boundaryEventName)).append("\n");
    sb.append("    destinationSubdomain: ").append(toIndentedString(destinationSubdomain)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

