

/*
 * Workflow
 * This API uses the workflow capability of SAP Build Process Automation. With the API, you can, for example, start new workflow instances and work with tasks.  Note: These APIs are designed for loosely coupled clients. This means:  - If SAP Build Process Automation adds fields to responses, the API version number does not increase. Your client must ignore new fields. - The order of fields in responses and of entries in arrays may change. This applies unless the API provides an explicit means to specify the desired order. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.demo.spa.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * The recipients of a mail task.
 */

// CHECKSTYLE:OFF
public class WorkflowInstanceExecutionLogRecipients 
// CHECKSTYLE:ON
{
  @JsonProperty("to")
  private List<String> to = new ArrayList<>();

  @JsonProperty("cc")
  private List<String> cc = new ArrayList<>();

  @JsonProperty("bcc")
  private List<String> bcc = new ArrayList<>();

  @JsonProperty("ignored")
  private List<String> ignored = new ArrayList<>();

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the to of this {@link WorkflowInstanceExecutionLogRecipients} instance and return the same instance.
   *
   * @param to  The &#39;to&#39; recipients.
   * @return The same instance of this {@link WorkflowInstanceExecutionLogRecipients} class
   */
   @Nonnull public WorkflowInstanceExecutionLogRecipients to(@Nonnull final List<String> to) {
    this.to = to;
    return this;
  }
  /**
  * Add one to instance to this {@link WorkflowInstanceExecutionLogRecipients}.
  * @param toItem The to that should be added
  * @return The same instance of type {@link WorkflowInstanceExecutionLogRecipients}
  */
  @Nonnull public WorkflowInstanceExecutionLogRecipients addtoItem( @Nonnull final String toItem) {
    if (this.to == null) {
      this.to = new ArrayList<>();
    }
    this.to.add(toItem);
    return this;
  }

   /**
   * The &#39;to&#39; recipients.
   * @return to  The to of this {@link WorkflowInstanceExecutionLogRecipients} instance.
  **/
  @Nonnull public List<String> getTo() {
    return to;
  }

  /**
  * Set the to of this {@link WorkflowInstanceExecutionLogRecipients} instance.
  *
  * @param to  The &#39;to&#39; recipients.
  */
  public void setTo( @Nonnull final List<String> to) {
    this.to = to;
  }

   /**
   * Set the cc of this {@link WorkflowInstanceExecutionLogRecipients} instance and return the same instance.
   *
   * @param cc  The &#39;cc&#39; recipients.
   * @return The same instance of this {@link WorkflowInstanceExecutionLogRecipients} class
   */
   @Nonnull public WorkflowInstanceExecutionLogRecipients cc(@Nonnull final List<String> cc) {
    this.cc = cc;
    return this;
  }
  /**
  * Add one cc instance to this {@link WorkflowInstanceExecutionLogRecipients}.
  * @param ccItem The cc that should be added
  * @return The same instance of type {@link WorkflowInstanceExecutionLogRecipients}
  */
  @Nonnull public WorkflowInstanceExecutionLogRecipients addccItem( @Nonnull final String ccItem) {
    if (this.cc == null) {
      this.cc = new ArrayList<>();
    }
    this.cc.add(ccItem);
    return this;
  }

   /**
   * The &#39;cc&#39; recipients.
   * @return cc  The cc of this {@link WorkflowInstanceExecutionLogRecipients} instance.
  **/
  @Nonnull public List<String> getCc() {
    return cc;
  }

  /**
  * Set the cc of this {@link WorkflowInstanceExecutionLogRecipients} instance.
  *
  * @param cc  The &#39;cc&#39; recipients.
  */
  public void setCc( @Nonnull final List<String> cc) {
    this.cc = cc;
  }

   /**
   * Set the bcc of this {@link WorkflowInstanceExecutionLogRecipients} instance and return the same instance.
   *
   * @param bcc  The &#39;bcc&#39; recipients.
   * @return The same instance of this {@link WorkflowInstanceExecutionLogRecipients} class
   */
   @Nonnull public WorkflowInstanceExecutionLogRecipients bcc(@Nonnull final List<String> bcc) {
    this.bcc = bcc;
    return this;
  }
  /**
  * Add one bcc instance to this {@link WorkflowInstanceExecutionLogRecipients}.
  * @param bccItem The bcc that should be added
  * @return The same instance of type {@link WorkflowInstanceExecutionLogRecipients}
  */
  @Nonnull public WorkflowInstanceExecutionLogRecipients addbccItem( @Nonnull final String bccItem) {
    if (this.bcc == null) {
      this.bcc = new ArrayList<>();
    }
    this.bcc.add(bccItem);
    return this;
  }

   /**
   * The &#39;bcc&#39; recipients.
   * @return bcc  The bcc of this {@link WorkflowInstanceExecutionLogRecipients} instance.
  **/
  @Nonnull public List<String> getBcc() {
    return bcc;
  }

  /**
  * Set the bcc of this {@link WorkflowInstanceExecutionLogRecipients} instance.
  *
  * @param bcc  The &#39;bcc&#39; recipients.
  */
  public void setBcc( @Nonnull final List<String> bcc) {
    this.bcc = bcc;
  }

   /**
   * Set the ignored of this {@link WorkflowInstanceExecutionLogRecipients} instance and return the same instance.
   *
   * @param ignored  The ignored recipients from \&quot;to\&quot;, \&quot;cc\&quot; and \&quot;bcc\&quot; fields if they exist.
   * @return The same instance of this {@link WorkflowInstanceExecutionLogRecipients} class
   */
   @Nonnull public WorkflowInstanceExecutionLogRecipients ignored(@Nonnull final List<String> ignored) {
    this.ignored = ignored;
    return this;
  }
  /**
  * Add one ignored instance to this {@link WorkflowInstanceExecutionLogRecipients}.
  * @param ignoredItem The ignored that should be added
  * @return The same instance of type {@link WorkflowInstanceExecutionLogRecipients}
  */
  @Nonnull public WorkflowInstanceExecutionLogRecipients addignoredItem( @Nonnull final String ignoredItem) {
    if (this.ignored == null) {
      this.ignored = new ArrayList<>();
    }
    this.ignored.add(ignoredItem);
    return this;
  }

   /**
   * The ignored recipients from \&quot;to\&quot;, \&quot;cc\&quot; and \&quot;bcc\&quot; fields if they exist.
   * @return ignored  The ignored of this {@link WorkflowInstanceExecutionLogRecipients} instance.
  **/
  @Nonnull public List<String> getIgnored() {
    return ignored;
  }

  /**
  * Set the ignored of this {@link WorkflowInstanceExecutionLogRecipients} instance.
  *
  * @param ignored  The ignored recipients from \&quot;to\&quot;, \&quot;cc\&quot; and \&quot;bcc\&quot; fields if they exist.
  */
  public void setIgnored( @Nonnull final List<String> ignored) {
    this.ignored = ignored;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link WorkflowInstanceExecutionLogRecipients}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link WorkflowInstanceExecutionLogRecipients} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("WorkflowInstanceExecutionLogRecipients has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link WorkflowInstanceExecutionLogRecipients} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final WorkflowInstanceExecutionLogRecipients workflowInstanceExecutionLogRecipients = (WorkflowInstanceExecutionLogRecipients) o;
    return Objects.equals(this.cloudSdkCustomFields, workflowInstanceExecutionLogRecipients.cloudSdkCustomFields) &&
        Objects.equals(this.to, workflowInstanceExecutionLogRecipients.to) &&
        Objects.equals(this.cc, workflowInstanceExecutionLogRecipients.cc) &&
        Objects.equals(this.bcc, workflowInstanceExecutionLogRecipients.bcc) &&
        Objects.equals(this.ignored, workflowInstanceExecutionLogRecipients.ignored);
  }

  @Override
  public int hashCode() {
    return Objects.hash(to, cc, bcc, ignored, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowInstanceExecutionLogRecipients {\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    cc: ").append(toIndentedString(cc)).append("\n");
    sb.append("    bcc: ").append(toIndentedString(bcc)).append("\n");
    sb.append("    ignored: ").append(toIndentedString(ignored)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

