

/*
 * Workflow
 * This API uses the workflow capability of SAP Build Process Automation. With the API, you can, for example, start new workflow instances and work with tasks.  Note: These APIs are designed for loosely coupled clients. This means:  - If SAP Build Process Automation adds fields to responses, the API version number does not increase. Your client must ignore new fields. - The order of fields in responses and of entries in arrays may change. This applies unless the API provides an explicit means to specify the desired order. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.demo.spa.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * WorkflowInstanceUpdatePayload
 */

// CHECKSTYLE:OFF
public class WorkflowInstanceUpdatePayload 
// CHECKSTYLE:ON
{
  /**
   * The new status of the workflow instance. The status values as required by this API have the following corresponding terms in user interfaces of SAP Build Process Automation: * RUNNING - Running * SUSPENDED - On Hold * CANCELED - Canceled
   */
  public enum StatusEnum {
    /**
    * The CANCELED option of this WorkflowInstanceUpdatePayload
    */
    CANCELED("CANCELED"),
    
    /**
    * The RUNNING option of this WorkflowInstanceUpdatePayload
    */
    RUNNING("RUNNING"),
    
    /**
    * The SUSPENDED option of this WorkflowInstanceUpdatePayload
    */
    SUSPENDED("SUSPENDED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type WorkflowInstanceUpdatePayload
    */
    @JsonCreator
    @Nonnull public static StatusEnum fromValue(@Nonnull final String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("status")
  private StatusEnum status;

  @JsonProperty("cascade")
  private Boolean cascade = false;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the status of this {@link WorkflowInstanceUpdatePayload} instance and return the same instance.
   *
   * @param status  The new status of the workflow instance. The status values as required by this API have the following corresponding terms in user interfaces of SAP Build Process Automation: * RUNNING - Running * SUSPENDED - On Hold * CANCELED - Canceled
   * @return The same instance of this {@link WorkflowInstanceUpdatePayload} class
   */
   @Nonnull public WorkflowInstanceUpdatePayload status(@Nonnull final StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * The new status of the workflow instance. The status values as required by this API have the following corresponding terms in user interfaces of SAP Build Process Automation: * RUNNING - Running * SUSPENDED - On Hold * CANCELED - Canceled
   * @return status  The status of this {@link WorkflowInstanceUpdatePayload} instance.
  **/
  @Nonnull public StatusEnum getStatus() {
    return status;
  }

  /**
  * Set the status of this {@link WorkflowInstanceUpdatePayload} instance.
  *
  * @param status  The new status of the workflow instance. The status values as required by this API have the following corresponding terms in user interfaces of SAP Build Process Automation: * RUNNING - Running * SUSPENDED - On Hold * CANCELED - Canceled
  */
  public void setStatus( @Nonnull final StatusEnum status) {
    this.status = status;
  }

   /**
   * Set the cascade of this {@link WorkflowInstanceUpdatePayload} instance and return the same instance.
   *
   * @param cascade  Indicate whether the statuses of the whole cascade of workflow instances are changed, including the workflow instance given in the API request as well as its subflow instances, or only of the given workflow instance. By default, no cascade to subflow instances happens.
   * @return The same instance of this {@link WorkflowInstanceUpdatePayload} class
   */
   @Nonnull public WorkflowInstanceUpdatePayload cascade(@Nonnull final Boolean cascade) {
    this.cascade = cascade;
    return this;
  }

   /**
   * Indicate whether the statuses of the whole cascade of workflow instances are changed, including the workflow instance given in the API request as well as its subflow instances, or only of the given workflow instance. By default, no cascade to subflow instances happens.
   * @return cascade  The cascade of this {@link WorkflowInstanceUpdatePayload} instance.
  **/
  @Nonnull public Boolean isCascade() {
    return cascade;
  }

  /**
  * Set the cascade of this {@link WorkflowInstanceUpdatePayload} instance.
  *
  * @param cascade  Indicate whether the statuses of the whole cascade of workflow instances are changed, including the workflow instance given in the API request as well as its subflow instances, or only of the given workflow instance. By default, no cascade to subflow instances happens.
  */
  public void setCascade( @Nonnull final Boolean cascade) {
    this.cascade = cascade;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link WorkflowInstanceUpdatePayload}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link WorkflowInstanceUpdatePayload} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("WorkflowInstanceUpdatePayload has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link WorkflowInstanceUpdatePayload} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final WorkflowInstanceUpdatePayload workflowInstanceUpdatePayload = (WorkflowInstanceUpdatePayload) o;
    return Objects.equals(this.cloudSdkCustomFields, workflowInstanceUpdatePayload.cloudSdkCustomFields) &&
        Objects.equals(this.status, workflowInstanceUpdatePayload.status) &&
        Objects.equals(this.cascade, workflowInstanceUpdatePayload.cascade);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, cascade, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowInstanceUpdatePayload {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    cascade: ").append(toIndentedString(cascade)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

