

/*
 * Workflow
 * This API uses the workflow capability of SAP Build Process Automation. With the API, you can, for example, start new workflow instances and work with tasks.  Note: These APIs are designed for loosely coupled clients. This means:  - If SAP Build Process Automation adds fields to responses, the API version number does not increase. Your client must ignore new fields. - The order of fields in responses and of entries in arrays may change. This applies unless the API provides an explicit means to specify the desired order. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.demo.spa.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.LinkedHashSet;
import java.util.Set;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * The changes made to the context or user task.
 */

// CHECKSTYLE:OFF
public class WorkflowInstanceExecutionLogChanges 
// CHECKSTYLE:ON
{
  @JsonProperty("create")
  private Set<String> create = new LinkedHashSet<>();

  @JsonProperty("update")
  private Set<String> update = new LinkedHashSet<>();

  @JsonProperty("delete")
  private Set<String> delete = new LinkedHashSet<>();

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the create of this {@link WorkflowInstanceExecutionLogChanges} instance and return the same instance.
   *
   * @param create  The variables, which were created in the context.
   * @return The same instance of this {@link WorkflowInstanceExecutionLogChanges} class
   */
   @Nonnull public WorkflowInstanceExecutionLogChanges create(@Nonnull final Set<String> create) {
    this.create = create;
    return this;
  }
  /**
  * Add one create instance to this {@link WorkflowInstanceExecutionLogChanges}.
  * @param createItem The create that should be added
  * @return The same instance of type {@link WorkflowInstanceExecutionLogChanges}
  */
  @Nonnull public WorkflowInstanceExecutionLogChanges addcreateItem( @Nonnull final String createItem) {
    if (this.create == null) {
      this.create = new LinkedHashSet<>();
    }
    this.create.add(createItem);
    return this;
  }

   /**
   * The variables, which were created in the context.
   * @return create  The create of this {@link WorkflowInstanceExecutionLogChanges} instance.
  **/
  @Nonnull public Set<String> getCreate() {
    return create;
  }

  /**
  * Set the create of this {@link WorkflowInstanceExecutionLogChanges} instance.
  *
  * @param create  The variables, which were created in the context.
  */
  public void setCreate( @Nonnull final Set<String> create) {
    this.create = create;
  }

   /**
   * Set the update of this {@link WorkflowInstanceExecutionLogChanges} instance and return the same instance.
   *
   * @param update  The variables, which were updated in the context or the user task attributes, which were updated.
   * @return The same instance of this {@link WorkflowInstanceExecutionLogChanges} class
   */
   @Nonnull public WorkflowInstanceExecutionLogChanges update(@Nonnull final Set<String> update) {
    this.update = update;
    return this;
  }
  /**
  * Add one update instance to this {@link WorkflowInstanceExecutionLogChanges}.
  * @param updateItem The update that should be added
  * @return The same instance of type {@link WorkflowInstanceExecutionLogChanges}
  */
  @Nonnull public WorkflowInstanceExecutionLogChanges addupdateItem( @Nonnull final String updateItem) {
    if (this.update == null) {
      this.update = new LinkedHashSet<>();
    }
    this.update.add(updateItem);
    return this;
  }

   /**
   * The variables, which were updated in the context or the user task attributes, which were updated.
   * @return update  The update of this {@link WorkflowInstanceExecutionLogChanges} instance.
  **/
  @Nonnull public Set<String> getUpdate() {
    return update;
  }

  /**
  * Set the update of this {@link WorkflowInstanceExecutionLogChanges} instance.
  *
  * @param update  The variables, which were updated in the context or the user task attributes, which were updated.
  */
  public void setUpdate( @Nonnull final Set<String> update) {
    this.update = update;
  }

   /**
   * Set the delete of this {@link WorkflowInstanceExecutionLogChanges} instance and return the same instance.
   *
   * @param delete  The variables, which were deleted from the context.
   * @return The same instance of this {@link WorkflowInstanceExecutionLogChanges} class
   */
   @Nonnull public WorkflowInstanceExecutionLogChanges delete(@Nonnull final Set<String> delete) {
    this.delete = delete;
    return this;
  }
  /**
  * Add one delete instance to this {@link WorkflowInstanceExecutionLogChanges}.
  * @param deleteItem The delete that should be added
  * @return The same instance of type {@link WorkflowInstanceExecutionLogChanges}
  */
  @Nonnull public WorkflowInstanceExecutionLogChanges adddeleteItem( @Nonnull final String deleteItem) {
    if (this.delete == null) {
      this.delete = new LinkedHashSet<>();
    }
    this.delete.add(deleteItem);
    return this;
  }

   /**
   * The variables, which were deleted from the context.
   * @return delete  The delete of this {@link WorkflowInstanceExecutionLogChanges} instance.
  **/
  @Nonnull public Set<String> getDelete() {
    return delete;
  }

  /**
  * Set the delete of this {@link WorkflowInstanceExecutionLogChanges} instance.
  *
  * @param delete  The variables, which were deleted from the context.
  */
  public void setDelete( @Nonnull final Set<String> delete) {
    this.delete = delete;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link WorkflowInstanceExecutionLogChanges}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link WorkflowInstanceExecutionLogChanges} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("WorkflowInstanceExecutionLogChanges has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link WorkflowInstanceExecutionLogChanges} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final WorkflowInstanceExecutionLogChanges workflowInstanceExecutionLogChanges = (WorkflowInstanceExecutionLogChanges) o;
    return Objects.equals(this.cloudSdkCustomFields, workflowInstanceExecutionLogChanges.cloudSdkCustomFields) &&
        Objects.equals(this.create, workflowInstanceExecutionLogChanges.create) &&
        Objects.equals(this.update, workflowInstanceExecutionLogChanges.update) &&
        Objects.equals(this.delete, workflowInstanceExecutionLogChanges.delete);
  }

  @Override
  public int hashCode() {
    return Objects.hash(create, update, delete, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowInstanceExecutionLogChanges {\n");
    sb.append("    create: ").append(toIndentedString(create)).append("\n");
    sb.append("    update: ").append(toIndentedString(update)).append("\n");
    sb.append("    delete: ").append(toIndentedString(delete)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

