

/*
 * Workflow
 * This API uses the workflow capability of SAP Build Process Automation. With the API, you can, for example, start new workflow instances and work with tasks.  Note: These APIs are designed for loosely coupled clients. This means:  - If SAP Build Process Automation adds fields to responses, the API version number does not increase. Your client must ignore new fields. - The order of fields in responses and of entries in arrays may change. This applies unless the API provides an explicit means to specify the desired order. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.demo.spa.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * WorkflowDefinitionVersion
 */

// CHECKSTYLE:OFF
public class WorkflowDefinitionVersion 
// CHECKSTYLE:ON
{
  @JsonProperty("id")
  private String id;

  @JsonProperty("name")
  private String name;

  @JsonProperty("version")
  private String version;

  @JsonProperty("createdAt")
  private OffsetDateTime createdAt;

  @JsonProperty("createdBy")
  private String createdBy;

  @JsonProperty("applicationScope")
  private String applicationScope;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the id of this {@link WorkflowDefinitionVersion} instance and return the same instance.
   *
   * @param id  The workflow definition ID. The ID is at most 64 characters long.
   * @return The same instance of this {@link WorkflowDefinitionVersion} class
   */
   @Nonnull public WorkflowDefinitionVersion id(@Nonnull final String id) {
    this.id = id;
    return this;
  }

   /**
   * The workflow definition ID. The ID is at most 64 characters long.
   * @return id  The id of this {@link WorkflowDefinitionVersion} instance.
  **/
  @Nonnull public String getId() {
    return id;
  }

  /**
  * Set the id of this {@link WorkflowDefinitionVersion} instance.
  *
  * @param id  The workflow definition ID. The ID is at most 64 characters long.
  */
  public void setId( @Nonnull final String id) {
    this.id = id;
  }

   /**
   * Set the name of this {@link WorkflowDefinitionVersion} instance and return the same instance.
   *
   * @param name  The workflow definition name. The name is at most 255 characters long.
   * @return The same instance of this {@link WorkflowDefinitionVersion} class
   */
   @Nonnull public WorkflowDefinitionVersion name(@Nonnull final String name) {
    this.name = name;
    return this;
  }

   /**
   * The workflow definition name. The name is at most 255 characters long.
   * @return name  The name of this {@link WorkflowDefinitionVersion} instance.
  **/
  @Nonnull public String getName() {
    return name;
  }

  /**
  * Set the name of this {@link WorkflowDefinitionVersion} instance.
  *
  * @param name  The workflow definition name. The name is at most 255 characters long.
  */
  public void setName( @Nonnull final String name) {
    this.name = name;
  }

   /**
   * Set the version of this {@link WorkflowDefinitionVersion} instance and return the same instance.
   *
   * @param version  The workflow definition version.
   * @return The same instance of this {@link WorkflowDefinitionVersion} class
   */
   @Nonnull public WorkflowDefinitionVersion version(@Nonnull final String version) {
    this.version = version;
    return this;
  }

   /**
   * The workflow definition version.
   * @return version  The version of this {@link WorkflowDefinitionVersion} instance.
  **/
  @Nonnull public String getVersion() {
    return version;
  }

  /**
  * Set the version of this {@link WorkflowDefinitionVersion} instance.
  *
  * @param version  The workflow definition version.
  */
  public void setVersion( @Nonnull final String version) {
    this.version = version;
  }

   /**
   * Set the createdAt of this {@link WorkflowDefinitionVersion} instance and return the same instance.
   *
   * @param createdAt  The time when the workflow definition was deployed.
   * @return The same instance of this {@link WorkflowDefinitionVersion} class
   */
   @Nonnull public WorkflowDefinitionVersion createdAt(@Nonnull final OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The time when the workflow definition was deployed.
   * @return createdAt  The createdAt of this {@link WorkflowDefinitionVersion} instance.
  **/
  @Nonnull public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  /**
  * Set the createdAt of this {@link WorkflowDefinitionVersion} instance.
  *
  * @param createdAt  The time when the workflow definition was deployed.
  */
  public void setCreatedAt( @Nonnull final OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

   /**
   * Set the createdBy of this {@link WorkflowDefinitionVersion} instance and return the same instance.
   *
   * @param createdBy  The user who deployed the workflow definition. The user ID is at most 255 characters long. This property may not be included for workflow definitions that were deployed before May 21, 2018.
   * @return The same instance of this {@link WorkflowDefinitionVersion} class
   */
   @Nonnull public WorkflowDefinitionVersion createdBy(@Nonnull final String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * The user who deployed the workflow definition. The user ID is at most 255 characters long. This property may not be included for workflow definitions that were deployed before May 21, 2018.
   * @return createdBy  The createdBy of this {@link WorkflowDefinitionVersion} instance.
  **/
  @Nonnull public String getCreatedBy() {
    return createdBy;
  }

  /**
  * Set the createdBy of this {@link WorkflowDefinitionVersion} instance.
  *
  * @param createdBy  The user who deployed the workflow definition. The user ID is at most 255 characters long. This property may not be included for workflow definitions that were deployed before May 21, 2018.
  */
  public void setCreatedBy( @Nonnull final String createdBy) {
    this.createdBy = createdBy;
  }

   /**
   * Set the applicationScope of this {@link WorkflowDefinitionVersion} instance and return the same instance.
   *
   * @param applicationScope  The scope to which the definition belongs. Either \&quot;own\&quot;, \&quot;shared\&quot; or a named scope.
   * @return The same instance of this {@link WorkflowDefinitionVersion} class
   */
   @Nonnull public WorkflowDefinitionVersion applicationScope(@Nonnull final String applicationScope) {
    this.applicationScope = applicationScope;
    return this;
  }

   /**
   * The scope to which the definition belongs. Either \&quot;own\&quot;, \&quot;shared\&quot; or a named scope.
   * @return applicationScope  The applicationScope of this {@link WorkflowDefinitionVersion} instance.
  **/
  @Nonnull public String getApplicationScope() {
    return applicationScope;
  }

  /**
  * Set the applicationScope of this {@link WorkflowDefinitionVersion} instance.
  *
  * @param applicationScope  The scope to which the definition belongs. Either \&quot;own\&quot;, \&quot;shared\&quot; or a named scope.
  */
  public void setApplicationScope( @Nonnull final String applicationScope) {
    this.applicationScope = applicationScope;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link WorkflowDefinitionVersion}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link WorkflowDefinitionVersion} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("WorkflowDefinitionVersion has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link WorkflowDefinitionVersion} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final WorkflowDefinitionVersion workflowDefinitionVersion = (WorkflowDefinitionVersion) o;
    return Objects.equals(this.cloudSdkCustomFields, workflowDefinitionVersion.cloudSdkCustomFields) &&
        Objects.equals(this.id, workflowDefinitionVersion.id) &&
        Objects.equals(this.name, workflowDefinitionVersion.name) &&
        Objects.equals(this.version, workflowDefinitionVersion.version) &&
        Objects.equals(this.createdAt, workflowDefinitionVersion.createdAt) &&
        Objects.equals(this.createdBy, workflowDefinitionVersion.createdBy) &&
        Objects.equals(this.applicationScope, workflowDefinitionVersion.applicationScope);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, version, createdAt, createdBy, applicationScope, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowDefinitionVersion {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    applicationScope: ").append(toIndentedString(applicationScope)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

