

/*
 * Workflow
 * This API uses the workflow capability of SAP Build Process Automation. With the API, you can, for example, start new workflow instances and work with tasks.  Note: These APIs are designed for loosely coupled clients. This means:  - If SAP Build Process Automation adds fields to responses, the API version number does not increase. Your client must ignore new fields. - The order of fields in responses and of entries in arrays may change. This applies unless the API provides an explicit means to specify the desired order. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.demo.spa.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import customer.demo.spa.model.CustomAttribute;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * WorkflowInstance
 */

// CHECKSTYLE:OFF
public class WorkflowInstance 
// CHECKSTYLE:ON
{
  @JsonProperty("definitionId")
  private String definitionId;

  @JsonProperty("definitionVersion")
  private String definitionVersion;

  @JsonProperty("id")
  private String id;

  @JsonProperty("startedAt")
  private OffsetDateTime startedAt;

  @JsonProperty("startedBy")
  private String startedBy;

  @JsonProperty("completedAt")
  private OffsetDateTime completedAt;

  /**
   * The status of the workflow instance. The status values as returned by this API have the following corresponding terms in user interfaces of SAP Build Process Automation: * RUNNING - Running * ERRONEOUS - Error * SUSPENDED - On Hold * CANCELED - Canceled * COMPLETED - Completed
   */
  public enum StatusEnum {
    /**
    * The RUNNING option of this WorkflowInstance
    */
    RUNNING("RUNNING"),
    
    /**
    * The ERRONEOUS option of this WorkflowInstance
    */
    ERRONEOUS("ERRONEOUS"),
    
    /**
    * The SUSPENDED option of this WorkflowInstance
    */
    SUSPENDED("SUSPENDED"),
    
    /**
    * The CANCELED option of this WorkflowInstance
    */
    CANCELED("CANCELED"),
    
    /**
    * The COMPLETED option of this WorkflowInstance
    */
    COMPLETED("COMPLETED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type WorkflowInstance
    */
    @JsonCreator
    @Nonnull public static StatusEnum fromValue(@Nonnull final String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("status")
  private StatusEnum status;

  @JsonProperty("businessKey")
  private String businessKey;

  @JsonProperty("subject")
  private String subject;

  @JsonProperty("rootInstanceId")
  private String rootInstanceId;

  @JsonProperty("parentInstanceId")
  private String parentInstanceId;

  @JsonProperty("applicationScope")
  private String applicationScope;

  @JsonProperty("projectId")
  private String projectId;

  @JsonProperty("projectVersion")
  private String projectVersion;

  @JsonProperty("attributes")
  private List<CustomAttribute> attributes = new ArrayList<>();

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the definitionId of this {@link WorkflowInstance} instance and return the same instance.
   *
   * @param definitionId  The ID of the workflow definition for which the instance was started. The ID is at most 64 characters long.
   * @return The same instance of this {@link WorkflowInstance} class
   */
   @Nonnull public WorkflowInstance definitionId(@Nonnull final String definitionId) {
    this.definitionId = definitionId;
    return this;
  }

   /**
   * The ID of the workflow definition for which the instance was started. The ID is at most 64 characters long.
   * @return definitionId  The definitionId of this {@link WorkflowInstance} instance.
  **/
  @Nonnull public String getDefinitionId() {
    return definitionId;
  }

  /**
  * Set the definitionId of this {@link WorkflowInstance} instance.
  *
  * @param definitionId  The ID of the workflow definition for which the instance was started. The ID is at most 64 characters long.
  */
  public void setDefinitionId( @Nonnull final String definitionId) {
    this.definitionId = definitionId;
  }

   /**
   * Set the definitionVersion of this {@link WorkflowInstance} instance and return the same instance.
   *
   * @param definitionVersion  The version of the workflow definition for which the instance was started.
   * @return The same instance of this {@link WorkflowInstance} class
   */
   @Nonnull public WorkflowInstance definitionVersion(@Nonnull final String definitionVersion) {
    this.definitionVersion = definitionVersion;
    return this;
  }

   /**
   * The version of the workflow definition for which the instance was started.
   * @return definitionVersion  The definitionVersion of this {@link WorkflowInstance} instance.
  **/
  @Nonnull public String getDefinitionVersion() {
    return definitionVersion;
  }

  /**
  * Set the definitionVersion of this {@link WorkflowInstance} instance.
  *
  * @param definitionVersion  The version of the workflow definition for which the instance was started.
  */
  public void setDefinitionVersion( @Nonnull final String definitionVersion) {
    this.definitionVersion = definitionVersion;
  }

   /**
   * Set the id of this {@link WorkflowInstance} instance and return the same instance.
   *
   * @param id  The workflow instance ID. The ID is at least 36 characters long.
   * @return The same instance of this {@link WorkflowInstance} class
   */
   @Nonnull public WorkflowInstance id(@Nonnull final String id) {
    this.id = id;
    return this;
  }

   /**
   * The workflow instance ID. The ID is at least 36 characters long.
   * @return id  The id of this {@link WorkflowInstance} instance.
  **/
  @Nonnull public String getId() {
    return id;
  }

  /**
  * Set the id of this {@link WorkflowInstance} instance.
  *
  * @param id  The workflow instance ID. The ID is at least 36 characters long.
  */
  public void setId( @Nonnull final String id) {
    this.id = id;
  }

   /**
   * Set the startedAt of this {@link WorkflowInstance} instance and return the same instance.
   *
   * @param startedAt  The time when the workflow instance started.
   * @return The same instance of this {@link WorkflowInstance} class
   */
   @Nonnull public WorkflowInstance startedAt(@Nonnull final OffsetDateTime startedAt) {
    this.startedAt = startedAt;
    return this;
  }

   /**
   * The time when the workflow instance started.
   * @return startedAt  The startedAt of this {@link WorkflowInstance} instance.
  **/
  @Nonnull public OffsetDateTime getStartedAt() {
    return startedAt;
  }

  /**
  * Set the startedAt of this {@link WorkflowInstance} instance.
  *
  * @param startedAt  The time when the workflow instance started.
  */
  public void setStartedAt( @Nonnull final OffsetDateTime startedAt) {
    this.startedAt = startedAt;
  }

   /**
   * Set the startedBy of this {@link WorkflowInstance} instance and return the same instance.
   *
   * @param startedBy  The user who started the workflow instance. The user ID is at most 255 characters long.
   * @return The same instance of this {@link WorkflowInstance} class
   */
   @Nonnull public WorkflowInstance startedBy(@Nonnull final String startedBy) {
    this.startedBy = startedBy;
    return this;
  }

   /**
   * The user who started the workflow instance. The user ID is at most 255 characters long.
   * @return startedBy  The startedBy of this {@link WorkflowInstance} instance.
  **/
  @Nonnull public String getStartedBy() {
    return startedBy;
  }

  /**
  * Set the startedBy of this {@link WorkflowInstance} instance.
  *
  * @param startedBy  The user who started the workflow instance. The user ID is at most 255 characters long.
  */
  public void setStartedBy( @Nonnull final String startedBy) {
    this.startedBy = startedBy;
  }

   /**
   * Set the completedAt of this {@link WorkflowInstance} instance and return the same instance.
   *
   * @param completedAt  The time when the workflow instance status changed to COMPLETED.
   * @return The same instance of this {@link WorkflowInstance} class
   */
   @Nonnull public WorkflowInstance completedAt(@Nonnull final OffsetDateTime completedAt) {
    this.completedAt = completedAt;
    return this;
  }

   /**
   * The time when the workflow instance status changed to COMPLETED.
   * @return completedAt  The completedAt of this {@link WorkflowInstance} instance.
  **/
  @Nonnull public OffsetDateTime getCompletedAt() {
    return completedAt;
  }

  /**
  * Set the completedAt of this {@link WorkflowInstance} instance.
  *
  * @param completedAt  The time when the workflow instance status changed to COMPLETED.
  */
  public void setCompletedAt( @Nonnull final OffsetDateTime completedAt) {
    this.completedAt = completedAt;
  }

   /**
   * Set the status of this {@link WorkflowInstance} instance and return the same instance.
   *
   * @param status  The status of the workflow instance. The status values as returned by this API have the following corresponding terms in user interfaces of SAP Build Process Automation: * RUNNING - Running * ERRONEOUS - Error * SUSPENDED - On Hold * CANCELED - Canceled * COMPLETED - Completed
   * @return The same instance of this {@link WorkflowInstance} class
   */
   @Nonnull public WorkflowInstance status(@Nonnull final StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * The status of the workflow instance. The status values as returned by this API have the following corresponding terms in user interfaces of SAP Build Process Automation: * RUNNING - Running * ERRONEOUS - Error * SUSPENDED - On Hold * CANCELED - Canceled * COMPLETED - Completed
   * @return status  The status of this {@link WorkflowInstance} instance.
  **/
  @Nonnull public StatusEnum getStatus() {
    return status;
  }

  /**
  * Set the status of this {@link WorkflowInstance} instance.
  *
  * @param status  The status of the workflow instance. The status values as returned by this API have the following corresponding terms in user interfaces of SAP Build Process Automation: * RUNNING - Running * ERRONEOUS - Error * SUSPENDED - On Hold * CANCELED - Canceled * COMPLETED - Completed
  */
  public void setStatus( @Nonnull final StatusEnum status) {
    this.status = status;
  }

   /**
   * Set the businessKey of this {@link WorkflowInstance} instance and return the same instance.
   *
   * @param businessKey  The business key of the workflow instance. The business key of a workflow instance is limited to 255 characters.
   * @return The same instance of this {@link WorkflowInstance} class
   */
   @Nonnull public WorkflowInstance businessKey(@Nonnull final String businessKey) {
    this.businessKey = businessKey;
    return this;
  }

   /**
   * The business key of the workflow instance. The business key of a workflow instance is limited to 255 characters.
   * @return businessKey  The businessKey of this {@link WorkflowInstance} instance.
  **/
  @Nonnull public String getBusinessKey() {
    return businessKey;
  }

  /**
  * Set the businessKey of this {@link WorkflowInstance} instance.
  *
  * @param businessKey  The business key of the workflow instance. The business key of a workflow instance is limited to 255 characters.
  */
  public void setBusinessKey( @Nonnull final String businessKey) {
    this.businessKey = businessKey;
  }

   /**
   * Set the subject of this {@link WorkflowInstance} instance and return the same instance.
   *
   * @param subject  The subject of the workflow instance. The subject of a workflow instance is limited to 255 characters.
   * @return The same instance of this {@link WorkflowInstance} class
   */
   @Nonnull public WorkflowInstance subject(@Nonnull final String subject) {
    this.subject = subject;
    return this;
  }

   /**
   * The subject of the workflow instance. The subject of a workflow instance is limited to 255 characters.
   * @return subject  The subject of this {@link WorkflowInstance} instance.
  **/
  @Nonnull public String getSubject() {
    return subject;
  }

  /**
  * Set the subject of this {@link WorkflowInstance} instance.
  *
  * @param subject  The subject of the workflow instance. The subject of a workflow instance is limited to 255 characters.
  */
  public void setSubject( @Nonnull final String subject) {
    this.subject = subject;
  }

   /**
   * Set the rootInstanceId of this {@link WorkflowInstance} instance and return the same instance.
   *
   * @param rootInstanceId  The workflow root instance ID. The root ID is at least 36 characters long.
   * @return The same instance of this {@link WorkflowInstance} class
   */
   @Nonnull public WorkflowInstance rootInstanceId(@Nonnull final String rootInstanceId) {
    this.rootInstanceId = rootInstanceId;
    return this;
  }

   /**
   * The workflow root instance ID. The root ID is at least 36 characters long.
   * @return rootInstanceId  The rootInstanceId of this {@link WorkflowInstance} instance.
  **/
  @Nonnull public String getRootInstanceId() {
    return rootInstanceId;
  }

  /**
  * Set the rootInstanceId of this {@link WorkflowInstance} instance.
  *
  * @param rootInstanceId  The workflow root instance ID. The root ID is at least 36 characters long.
  */
  public void setRootInstanceId( @Nonnull final String rootInstanceId) {
    this.rootInstanceId = rootInstanceId;
  }

   /**
   * Set the parentInstanceId of this {@link WorkflowInstance} instance and return the same instance.
   *
   * @param parentInstanceId  The workflow parent instance ID. The parent ID can be null or at least 36 characters long.
   * @return The same instance of this {@link WorkflowInstance} class
   */
   @Nonnull public WorkflowInstance parentInstanceId(@Nonnull final String parentInstanceId) {
    this.parentInstanceId = parentInstanceId;
    return this;
  }

   /**
   * The workflow parent instance ID. The parent ID can be null or at least 36 characters long.
   * @return parentInstanceId  The parentInstanceId of this {@link WorkflowInstance} instance.
  **/
  @Nonnull public String getParentInstanceId() {
    return parentInstanceId;
  }

  /**
  * Set the parentInstanceId of this {@link WorkflowInstance} instance.
  *
  * @param parentInstanceId  The workflow parent instance ID. The parent ID can be null or at least 36 characters long.
  */
  public void setParentInstanceId( @Nonnull final String parentInstanceId) {
    this.parentInstanceId = parentInstanceId;
  }

   /**
   * Set the applicationScope of this {@link WorkflowInstance} instance and return the same instance.
   *
   * @param applicationScope  The scope to which the workflow instance belongs. Either \&quot;own\&quot;, \&quot;shared\&quot;, or a named scope.
   * @return The same instance of this {@link WorkflowInstance} class
   */
   @Nonnull public WorkflowInstance applicationScope(@Nonnull final String applicationScope) {
    this.applicationScope = applicationScope;
    return this;
  }

   /**
   * The scope to which the workflow instance belongs. Either \&quot;own\&quot;, \&quot;shared\&quot;, or a named scope.
   * @return applicationScope  The applicationScope of this {@link WorkflowInstance} instance.
  **/
  @Nonnull public String getApplicationScope() {
    return applicationScope;
  }

  /**
  * Set the applicationScope of this {@link WorkflowInstance} instance.
  *
  * @param applicationScope  The scope to which the workflow instance belongs. Either \&quot;own\&quot;, \&quot;shared\&quot;, or a named scope.
  */
  public void setApplicationScope( @Nonnull final String applicationScope) {
    this.applicationScope = applicationScope;
  }

   /**
   * Set the projectId of this {@link WorkflowInstance} instance and return the same instance.
   *
   * @param projectId  The project ID  of the SAP Build Process Automation project to which workflowinstance belongs to. It has the format of region.subaccount.projectName. The projectid is limited to 255 characters.
   * @return The same instance of this {@link WorkflowInstance} class
   */
   @Nonnull public WorkflowInstance projectId(@Nonnull final String projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * The project ID  of the SAP Build Process Automation project to which workflowinstance belongs to. It has the format of region.subaccount.projectName. The projectid is limited to 255 characters.
   * @return projectId  The projectId of this {@link WorkflowInstance} instance.
  **/
  @Nonnull public String getProjectId() {
    return projectId;
  }

  /**
  * Set the projectId of this {@link WorkflowInstance} instance.
  *
  * @param projectId  The project ID  of the SAP Build Process Automation project to which workflowinstance belongs to. It has the format of region.subaccount.projectName. The projectid is limited to 255 characters.
  */
  public void setProjectId( @Nonnull final String projectId) {
    this.projectId = projectId;
  }

   /**
   * Set the projectVersion of this {@link WorkflowInstance} instance and return the same instance.
   *
   * @param projectVersion  The project version of SAP Build Process Automation project to which workflowinstance belongs to. The projectversion is limited to 64 characters.
   * @return The same instance of this {@link WorkflowInstance} class
   */
   @Nonnull public WorkflowInstance projectVersion(@Nonnull final String projectVersion) {
    this.projectVersion = projectVersion;
    return this;
  }

   /**
   * The project version of SAP Build Process Automation project to which workflowinstance belongs to. The projectversion is limited to 64 characters.
   * @return projectVersion  The projectVersion of this {@link WorkflowInstance} instance.
  **/
  @Nonnull public String getProjectVersion() {
    return projectVersion;
  }

  /**
  * Set the projectVersion of this {@link WorkflowInstance} instance.
  *
  * @param projectVersion  The project version of SAP Build Process Automation project to which workflowinstance belongs to. The projectversion is limited to 64 characters.
  */
  public void setProjectVersion( @Nonnull final String projectVersion) {
    this.projectVersion = projectVersion;
  }

   /**
   * Set the attributes of this {@link WorkflowInstance} instance and return the same instance.
   *
   * @param attributes  Attributes of the workflow instance. Present only if the $expand parameter in the query has the value \&quot;attributes\&quot;.
   * @return The same instance of this {@link WorkflowInstance} class
   */
   @Nonnull public WorkflowInstance attributes(@Nonnull final List<CustomAttribute> attributes) {
    this.attributes = attributes;
    return this;
  }
  /**
  * Add one attributes instance to this {@link WorkflowInstance}.
  * @param attributesItem The attributes that should be added
  * @return The same instance of type {@link WorkflowInstance}
  */
  @Nonnull public WorkflowInstance addattributesItem( @Nonnull final CustomAttribute attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Attributes of the workflow instance. Present only if the $expand parameter in the query has the value \&quot;attributes\&quot;.
   * @return attributes  The attributes of this {@link WorkflowInstance} instance.
  **/
  @Nonnull public List<CustomAttribute> getAttributes() {
    return attributes;
  }

  /**
  * Set the attributes of this {@link WorkflowInstance} instance.
  *
  * @param attributes  Attributes of the workflow instance. Present only if the $expand parameter in the query has the value \&quot;attributes\&quot;.
  */
  public void setAttributes( @Nonnull final List<CustomAttribute> attributes) {
    this.attributes = attributes;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link WorkflowInstance}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link WorkflowInstance} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("WorkflowInstance has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link WorkflowInstance} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final WorkflowInstance workflowInstance = (WorkflowInstance) o;
    return Objects.equals(this.cloudSdkCustomFields, workflowInstance.cloudSdkCustomFields) &&
        Objects.equals(this.definitionId, workflowInstance.definitionId) &&
        Objects.equals(this.definitionVersion, workflowInstance.definitionVersion) &&
        Objects.equals(this.id, workflowInstance.id) &&
        Objects.equals(this.startedAt, workflowInstance.startedAt) &&
        Objects.equals(this.startedBy, workflowInstance.startedBy) &&
        Objects.equals(this.completedAt, workflowInstance.completedAt) &&
        Objects.equals(this.status, workflowInstance.status) &&
        Objects.equals(this.businessKey, workflowInstance.businessKey) &&
        Objects.equals(this.subject, workflowInstance.subject) &&
        Objects.equals(this.rootInstanceId, workflowInstance.rootInstanceId) &&
        Objects.equals(this.parentInstanceId, workflowInstance.parentInstanceId) &&
        Objects.equals(this.applicationScope, workflowInstance.applicationScope) &&
        Objects.equals(this.projectId, workflowInstance.projectId) &&
        Objects.equals(this.projectVersion, workflowInstance.projectVersion) &&
        Objects.equals(this.attributes, workflowInstance.attributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(definitionId, definitionVersion, id, startedAt, startedBy, completedAt, status, businessKey, subject, rootInstanceId, parentInstanceId, applicationScope, projectId, projectVersion, attributes, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowInstance {\n");
    sb.append("    definitionId: ").append(toIndentedString(definitionId)).append("\n");
    sb.append("    definitionVersion: ").append(toIndentedString(definitionVersion)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    startedBy: ").append(toIndentedString(startedBy)).append("\n");
    sb.append("    completedAt: ").append(toIndentedString(completedAt)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    businessKey: ").append(toIndentedString(businessKey)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    rootInstanceId: ").append(toIndentedString(rootInstanceId)).append("\n");
    sb.append("    parentInstanceId: ").append(toIndentedString(parentInstanceId)).append("\n");
    sb.append("    applicationScope: ").append(toIndentedString(applicationScope)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    projectVersion: ").append(toIndentedString(projectVersion)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

