

/*
 * Workflow
 * This API uses the workflow capability of SAP Build Process Automation. With the API, you can, for example, start new workflow instances and work with tasks.  Note: These APIs are designed for loosely coupled clients. This means:  - If SAP Build Process Automation adds fields to responses, the API version number does not increase. Your client must ignore new fields. - The order of fields in responses and of entries in arrays may change. This applies unless the API provides an explicit means to specify the desired order. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.demo.spa.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * WorkflowDefinitionJob
 */

// CHECKSTYLE:OFF
public class WorkflowDefinitionJob 
// CHECKSTYLE:ON
{
  @JsonProperty("id")
  private String id;

  /**
   * The purpose of the job.
   */
  public enum PurposeEnum {
    /**
    * The DELETE option of this WorkflowDefinitionJob
    */
    DELETE("delete");

    private String value;

    PurposeEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type WorkflowDefinitionJob
    */
    @JsonCreator
    @Nonnull public static PurposeEnum fromValue(@Nonnull final String value) {
      for (PurposeEnum b : PurposeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("purpose")
  private PurposeEnum purpose;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the id of this {@link WorkflowDefinitionJob} instance and return the same instance.
   *
   * @param id  The job ID. The ID is at least 36 characters long.
   * @return The same instance of this {@link WorkflowDefinitionJob} class
   */
   @Nonnull public WorkflowDefinitionJob id(@Nonnull final String id) {
    this.id = id;
    return this;
  }

   /**
   * The job ID. The ID is at least 36 characters long.
   * @return id  The id of this {@link WorkflowDefinitionJob} instance.
  **/
  @Nonnull public String getId() {
    return id;
  }

  /**
  * Set the id of this {@link WorkflowDefinitionJob} instance.
  *
  * @param id  The job ID. The ID is at least 36 characters long.
  */
  public void setId( @Nonnull final String id) {
    this.id = id;
  }

   /**
   * Set the purpose of this {@link WorkflowDefinitionJob} instance and return the same instance.
   *
   * @param purpose  The purpose of the job.
   * @return The same instance of this {@link WorkflowDefinitionJob} class
   */
   @Nonnull public WorkflowDefinitionJob purpose(@Nonnull final PurposeEnum purpose) {
    this.purpose = purpose;
    return this;
  }

   /**
   * The purpose of the job.
   * @return purpose  The purpose of this {@link WorkflowDefinitionJob} instance.
  **/
  @Nonnull public PurposeEnum getPurpose() {
    return purpose;
  }

  /**
  * Set the purpose of this {@link WorkflowDefinitionJob} instance.
  *
  * @param purpose  The purpose of the job.
  */
  public void setPurpose( @Nonnull final PurposeEnum purpose) {
    this.purpose = purpose;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link WorkflowDefinitionJob}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link WorkflowDefinitionJob} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("WorkflowDefinitionJob has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link WorkflowDefinitionJob} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final WorkflowDefinitionJob workflowDefinitionJob = (WorkflowDefinitionJob) o;
    return Objects.equals(this.cloudSdkCustomFields, workflowDefinitionJob.cloudSdkCustomFields) &&
        Objects.equals(this.id, workflowDefinitionJob.id) &&
        Objects.equals(this.purpose, workflowDefinitionJob.purpose);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, purpose, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowDefinitionJob {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    purpose: ").append(toIndentedString(purpose)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

